import java.nio.file.*;
import java.util.*;
import thinkthen.*;
import thinkthen.Complete.*;
import thinkthen.Requests.*;
import thinkthen.CompleteEngine.CompleteCall;

/** Shared fixture adapter: JSON is input framing; known outputs use typed native getters. */
public final class NativeCases {
 public static String frame(){try {StringBuilder s=new StringBuilder();int ch;while((ch=System.in.read())!=-1&&ch!='\n')s.append((char)ch);return new String(s.toString().getBytes(java.nio.charset.StandardCharsets.ISO_8859_1),java.nio.charset.StandardCharsets.UTF_8);}catch(java.io.IOException f){throw new java.io.UncheckedIOException(f);}}

 static Object opt(OptionalValue<?> v){return v.present()?v.value():null;}
 static Content content(Object v,boolean text){return text&&v instanceof String s?new Content(ContentKind.TEXT,s,null):new Content(ContentKind.JSON,"",v);}
 static Object original(Content c){return c.kind()==ContentKind.TEXT?c.text():c.json();}
 static boolean yes(Map<String,Object> d,String k){return Boolean.TRUE.equals(d.get(k));}
 @SuppressWarnings("unchecked") static Map<String,Object> map(Object v){return v instanceof Map<?,?> m?(Map<String,Object>)m:new LinkedHashMap<>();}
 @SuppressWarnings("unchecked") static List<Object> list(Object v){return v instanceof List<?> l?(List<Object>)l:List.of();}
 static QuestionInput question(Map<String,Object> d){String verb=(String)d.get("verb");Map<String,Object> q=map(d.get("question"));QuestionRole role=switch(verb){case "annotate"->QuestionRole.SET;case "rank"->q.containsKey("questions")?QuestionRole.RANK_SET:QuestionRole.RANK;case "find"->QuestionRole.FIND;case "recognize"->QuestionRole.RECOGNIZE;case "relate"->QuestionRole.RELATE;case "choose"->q.containsKey("options")?QuestionRole.ATOMIC:QuestionRole.DYNAMIC_CHOOSE;default->QuestionRole.ATOMIC;};
  String loader=(String)d.getOrDefault("loader","");if(loader==null)loader="";
  if(loader.equals("load_named")||loader.equals("named"))return QuestionInput.namedQuestion(role,(String)d.get("reference"));
  if(loader.equals("load_reference")||loader.equals("reference"))return QuestionInput.questionReference(role,(String)d.get("reference"));
  if(loader.equals("load")||loader.equals("file"))return QuestionInput.questionFile((String)d.get("reference"));
  if("file".equals(d.get("question_form")))return QuestionInput.questionFile("fixture-question.json");
  if(verb.equals("find")&&yes(q,"none")){Question b=Questions.find(content(q.get("find"),true));return QuestionInput.asked(new Question(b.kind(),b.text(),b.yes(),b.no(),b.choices(),b.threshold(),b.relationThreshold(),b.model(),b.profile(),b.batch(),b.batchMax(),true,b.on(),b.members(),b.kinds(),b.relations(),b.namePointer(),b.kindPointer(),map(d.get("metadata")).isEmpty()?OptionalValue.absent():OptionalValue.of(new CompleteDetails.QuestionAuthor(OptionalValue.of((String)map(d.get("metadata")).get("name")),OptionalValue.of(((Number)map(d.get("metadata")).get("wording_version")).longValue()),new CompleteDetails.InputDeclaration(CompleteDetails.DeclarationKind.ABSENT,List.of(),List.of()),new CompleteDetails.InputDeclaration(CompleteDetails.DeclarationKind.ABSENT,List.of(),List.of())))));}
  return QuestionInput.savedQuestion(role,d.get("raw") instanceof String s?s:Json.write(q));
 }
 static InputSource source(Map<String,Object> d)throws java.io.IOException{
  if(!list(d.get("paths")).isEmpty())return InputSource.files(new FileSource(list(d.get("paths")).stream().map(String.class::cast).toList(),SourceUnit.values()[((Number)d.get("source_unit")).intValue()-1],((Number)d.getOrDefault("window",0)).longValue(),yes(d,"image_reader")));
  List<ImageInput> images=new ArrayList<>();for(Object p:list(d.get("image_paths")))images.add(new ImageInput("image/jpeg".equals(d.get("media"))?Media.JPEG:Media.PNG,Files.readAllBytes(Path.of((String)p)),OptionalValue.absent()));
  List<RecordInput> records=new ArrayList<>();int at=0;for(Object item:list(d.get("items"))){Object original=yes(d,"caption_files")?Files.readString(Path.of("caption-"+at+".txt")):item;List<Choice> options=list(d.get("candidate_orders")).isEmpty()?List.of():list(list(d.get("candidate_orders")).get(at)).stream().map(n->new Choice((String)n,OptionalValue.absent(),OptionalValue.absent())).toList();at++;records.add(new RecordInput(yes(d,"image_only")?OptionalValue.absent():OptionalValue.of(content(original,yes(d,"text"))),yes(d,"context_present")?OptionalValue.of(content(d.get("context"),true)):OptionalValue.absent(),options,images));}return InputSource.records(records);
 }
 public static String run(CompleteEngine e,Map<String,Object> d,Door.Token token){Thread cancellation=null;try{
 if(yes(d,"held_cancel")){cancellation=Thread.ofPlatform().start(()->{try{if(System.in.read()!='!')throw new IllegalStateException("missing cancellation signal");token.fire();System.out.println("cancel-fired");System.out.flush();}catch(java.io.IOException f){throw new java.io.UncheckedIOException(f);}});}
  QuestionInput q=question(d);InputSource s=source(d);CallControls c=new CallControls(d.get("shared_context")==null?OptionalValue.absent():OptionalValue.of(content(d.get("shared_context"),true)),OptionalValue.absent(),false,true);
  String injection=(String)map(d.get("operation")).get("injection");if("cancel_token".equals(injection))token.fire();long deadline="expired_deadline".equals(injection)?0:-1;
  if(yes(d,"incremental")){NativeBatch<?> batch=switch((String)d.get("verb")){
case "decide"->e.decideBatch(q,s,c,deadline,token);case "choose"->e.chooseBatch(q,s,c,deadline,token);case "tag"->e.tagBatch(q,s,c,deadline,token);case "score"->e.scoreBatch(q,s,c,deadline,token);case "filter"->e.filterBatch(q,s,c,deadline,token);case "annotate"->e.annotateBatch(q,s,c,deadline,token);default->throw new IllegalArgumentException("function has no native batch");};return Json.write(batch(batch));}
  CompleteCall<?> call=switch((String)d.get("verb")){
   case "decide"->e.decideComplete(q,s,c,deadline,token);case "choose"->e.chooseComplete(q,s,c,deadline,token);case "tag"->e.tagComplete(q,s,c,deadline,token);case "score"->e.scoreComplete(q,s,c,deadline,token);case "filter"->e.filterComplete(q,s,c,deadline,token);case "rank"->e.rankComplete(q,s,c,deadline,token);case "find"->e.findComplete(q,s,c,deadline,token);case "annotate"->e.annotateComplete(q,s,c,deadline,token);case "recognize"->e.recognizeComplete(q,s,c,deadline,token);case "relate"->e.relateComplete(q,s,c,deadline,token);default->throw new IllegalArgumentException("unknown function");};return Json.write(normalize(call));
 }catch(Door.NativeFailure f){return Json.write(error(f.failure.code(),f.failure.message(),f.complete));}catch(java.io.IOException f){throw new java.io.UncheckedIOException(f);}finally{if(cancellation!=null)try{cancellation.join();}catch(InterruptedException f){Thread.currentThread().interrupt();throw new IllegalStateException(f);}}}
 static Map<String,Object> batch(NativeBatch<?> batch){List<Object> rows=new ArrayList<>();try(batch){try{while(true){CompleteCall<?> part=batch.next();if(part==null)break;Map<String,Object> out=normalize(part);if(!Objects.equals(out.get("code"),0)){out.put("completed",rows);return out;}for(Object row:part.rows())rows.add(row(row,part.observations()));}Map<String,Object> out=normalize(batch.facts());out.put("completed",rows);out.put("rows",rows);return out;}catch(Door.NativeFailure f){Map<String,Object> out=error(f.failure.code(),f.failure.message(),f.complete);out.put("completed",rows);return out;}}}
 public static String failure(Door.NativeFailure f){return Json.write(error(f.failure.code(),f.failure.message(),f.complete));}
 static Map<String,Object> error(long code,String message,OptionalValue<CompleteError> detail){Map<String,Object> out=new LinkedHashMap<>();out.put("code",code);out.put("message",message);if(detail.present()){CompleteError e=detail.value();if(e.facts().present()){out.put("requests_sent",e.facts().value().requestsSent());out.put("records",e.facts().value().records());}if(e.stopped().present())out.put("stopped_at",opt(e.stopped().value().at()));}return out;}
 static Map<String,Object> normalize(CompleteCall<?> c){if(c.error().present())return error(c.error().value().code(),c.error().value().message(),c.error());Map<String,Object> out=new LinkedHashMap<>();out.put("code",0);out.put("schema",c.schema());out.put("observations",c.observations().size());if(c.facts().present()){out.put("call_id",c.facts().value().callId().value());out.put("requests_sent",c.facts().value().requestsSent());out.put("cache_answers",c.facts().value().cacheAnswers());out.put("records",c.facts().value().records());if(c.facts().value().inputTokens().present())out.put("input_tokens",c.facts().value().inputTokens().value());if(c.facts().value().outputTokens().present())out.put("output_tokens",c.facts().value().outputTokens().value());}out.put("rows",c.rows().stream().map(r->row(r,c.observations())).toList());return out;}
 static Object decide(DecideValue v){return switch(v.kind()){case NULL->null;case BOOLEAN->v.booleanValue();case AUTHORED->original(v.authored().value());};}
 static Object member(MemberValue v){return switch(v.function()){case DECIDE->decide(v.decide().value());case CHOOSE->opt(v.choose());case TAG->opt(v.tag());case SCORE->opt(v.score());default->throw new IllegalArgumentException("non-atomic member");};}
 static Object entity(Entity e){return Map.of("text",e.text(),"start",e.start(),"end",e.end(),"length",e.length(),"kind",e.kind(),"strength",e.strength());}
 static Object endpoint(Endpoint e){return Map.of("name",e.name(),"kind",e.kind());}
 static Object edge(String relation,Object source,Object target,double probability,boolean either){Map<String,Object> out=new LinkedHashMap<>();out.put("relation",relation);out.put("source",source);out.put("target",target);out.put("probability",probability);if(either)out.put("either",true);return out;}
 static Object edges(List<Edge> v){return v.stream().map(e->edge(e.relation(),endpoint(e.source()),endpoint(e.target()),e.probability(),e.either())).toList();}
 static Object recognized(RecognizeValue v){Map<String,Object> out=new LinkedHashMap<>();out.put("entities",v.entities().stream().map(NativeCases::entity).toList());if(v.relations().present())out.put("relations",v.relations().value().stream().map(e->edge(e.relation(),entity(e.source()),entity(e.target()),e.probability(),e.either())).toList());return out;}
 static CommonRow common(Object row){return switch(row){case DecideRow r->r.common();case ChooseRow r->r.common();case TagRow r->r.common();case ScoreRow r->r.common();case FilterRow r->r.common();case RankRow r->r.common();case FindRow r->r.common();case AnnotateRow r->r.common();case RecognizeRow r->r.common();case RelateRow r->r.common();default->throw new IllegalArgumentException("unknown row");};}
 static Object observed(RowValue r){return switch(r.function()){case DECIDE->r.decide().value();case CHOOSE->r.choose().value();case TAG->r.tag().value();case SCORE->r.score().value();case FILTER->r.filter().value();case RANK->r.rank().value();case FIND->r.find().value();case ANNOTATE->r.annotate().value();case RECOGNIZE->r.recognize().value();case RELATE->r.relate().value();};}
 static void location(Map<String,Object> out,OptionalValue<Location> p){if(p.present()){Location l=p.value();if(l.file().present())out.put("file",l.file().value());if(l.firstLine().present())out.put("first_line",l.firstLine().value());if(l.lastLine().present())out.put("last_line",l.lastLine().value());}}
 static Map<String,Object> author(CompleteDetails.QuestionAuthor a){Map<String,Object> out=new LinkedHashMap<>();if(a!=null){if(a.name().present())out.put("name",a.name().value());if(a.wordingVersion().present())out.put("wording_version",a.wordingVersion().value());}return out;}
 static Map<String,Object> row(Object r,List<ObservationEvent> events){CommonRow c=common(r);Object value=switch(r){case DecideRow x->decide(x.value());case ChooseRow x->opt(x.value());case TagRow x->x.value();case ScoreRow x->x.value();case FilterRow x->x.value();case RankRow x->opt(x.value());case FindRow x->x.value().present()?original(x.value().value()):null;case AnnotateRow x->{Map<String,Object> members=new LinkedHashMap<>();for(AnnotationMember m:x.answers())members.put(m.name(),m.success().present()?member(m.success().value().value()):Map.of("failed",Map.of("kind","backend","cause",snake(m.failure().value().cause().name()))));yield members;}case RecognizeRow x->recognized(x.value());case RelateRow x->edges(x.value());default->throw new IllegalArgumentException("unknown row");};
  Map<String,Object> out=new LinkedHashMap<>();long index=0;for(ObservationEvent event:events)if(event.row().present()&&common(observed(event.row().value().value())).answerId().equals(c.answerId())){index=event.row().value().index();break;}
  out.put("index",r instanceof FindRow x?opt(x.index()):index);out.put("value",value);out.put("answer_id",c.answerId().value());out.put("origin",c.meta().origin().present()?c.meta().origin().value().ordinal()+1:null);out.put("answered_by",opt(c.meta().answeredBy()));out.put("observations",c.meta().observations().size());out.put("sources",c.meta().questionSources().size());out.put("input",c.input().present()?original(c.input().value()):null);location(out,c.position());out.putAll(author(c.author()));
  out.put("observation_ids",c.meta().observations().stream().filter(i->i.observationId().present()).map(i->i.observationId().value().value()).toList());if(c.images().present())out.put("image_properties",c.images().value().stream().map(i->List.of(i.media().ordinal()+1,i.width(),i.height())).toList());if(c.images().present())out.put("images",c.images().value().stream().map(i->HexFormat.of().formatHex(i.bytes())).toList());
  if(c.answer().present()){AtomicAnswer a=c.answer().value();out.put("answer_kind",a.kind().name().toLowerCase(Locale.ROOT));if(a.probability().present())out.put("probability",a.probability().value());else{Map<String,Object> ps=new LinkedHashMap<>();for(Probability p:a.probabilities())ps.put(p.name(),p.probability());out.put("probabilities",ps);}}
  out.put("detail_inputs",c.details().inputs().stream().map(i->{Map<String,Object> input=new LinkedHashMap<>();input.put("input",i.original().present()?original(i.original().value()):null);location(input,i.position());return input;}).toList());if(r instanceof AnnotateRow a)out.put("member_authors",a.answers().stream().map(m->author(m.author())).toList());if(r instanceof RankRow rank&&!rank.members().isEmpty()){rankFacts(out,c);out.put("question_name",opt(rank.questionName()));out.put("members",rank.members().stream().map(m->{Map<String,Object> child=row(m,List.of());child.put("name",opt(m.questionName()));child.put("author",opt(m.common().author().name()));rankFacts(child,m.common());return child;}).toList());}return out;
 }
 static void rankFacts(Map<String,Object> out,CommonRow c){out.put("model",c.meta().model());out.put("context_digest",c.meta().contextSha256().present()?c.meta().contextSha256().value().value():null);Map<String,Object> usage=new LinkedHashMap<>();if(c.details().usage().inputTokens().present())usage.put("input_tokens",c.details().usage().inputTokens().value());if(c.details().usage().outputTokens().present())usage.put("output_tokens",c.details().usage().outputTokens().value());out.put("usage",usage);out.put("source_batch_sizes",c.details().questionSources().stream().map(s->opt(s.batchSize())).toList());}
 static String snake(String s){return s.toLowerCase(Locale.ROOT);}
}
