with Interfaces.C;
with System;
with Thinkthen; use Thinkthen;
with Thinkthen.Typed; use Thinkthen.Typed;
with Thinkthen.Typed.Complete; use Thinkthen.Typed.Complete;
with Thinkthen_C_Inputs; use Thinkthen_C_Inputs;
with Thinkthen_C_Rows; use Thinkthen_C_Rows;
with Thinkthen_C_Events; use Thinkthen_C_Events;
procedure Typed_Consumer is
   Client : Engine;
   Q : Question;
   Input : Source;
   Picture : Image;
   Output : Result;
   Options : Controls_V1 := Controls;
   Code : Interfaces.C.int;
   Spec : Question_Spec_V1;
   Source_Spec : Source_Spec_V1;
   Rows : Record_Array (1 .. 1);
   Image_Info : Image_View_V1;
   Header : Summary_V1;
   Event : Observation_V1;
   Decide_Row : Decide_View_V1;
   Choose_Row : Choose_View_V1;
   Tag_Row : Tag_View_V1;
   Score_Row : Score_View_V1;
   Filter_Row : Filter_View_V1;
   Rank_Row : Rank_View_V1;
   Find_Row : Find_View_V1;
   Annotate_Row : Annotate_View_V1;
   Recognize_Row : Recognize_View_V1;
   Relate_Row : Relate_View_V1;
begin
   New_Question (Client, Spec, Q, Code);
   Load_Question (Client, (others => <>), Q, Code);
   Clone_Image (Client, System.Null_Address, 0, C_IMAGE_PNG_V1, (others => <>), Picture, Code);
   Image_View (Picture, Image_Info, Code);
   Records (Client, Rows, Input, Code);
   Files (Client, Source_Spec, Input, Code);
   Decide (Client, Q, Input, Options, Output, Code);
   Decide (Output, 0, Decide_Row, Code);
   Choose (Client, Q, Input, Options, Output, Code);
   Choose (Output, 0, Choose_Row, Code);
   Tag (Client, Q, Input, Options, Output, Code);
   Tag (Output, 0, Tag_Row, Code);
   Score (Client, Q, Input, Options, Output, Code);
   Score (Output, 0, Score_Row, Code);
   Filter (Client, Q, Input, Options, Output, Code);
   Filter (Output, 0, Filter_Row, Code);
   Rank (Client, Q, Input, Options, Output, Code);
   Rank (Output, 0, Rank_Row, Code);
   Find (Client, Q, Input, Options, Output, Code);
   Find (Output, 0, Find_Row, Code);
   Annotate (Client, Q, Input, Options, Output, Code);
   Annotate (Output, 0, Annotate_Row, Code);
   Recognize (Client, Q, Input, Options, Output, Code);
   Recognize (Output, 0, Recognize_Row, Code);
   Relate (Client, Q, Input, Options, Output, Code);
   Relate (Output, 0, Relate_Row, Code);
   Summary (Output, Header, Code);
   Observation (Output, 0, Event, Code);
   Error_Snapshot (Client, Output, Code);
   Error_Snapshot (Output, Code);
end Typed_Consumer;
