with Interfaces; use Interfaces;
with Interfaces.C; use Interfaces.C;
with Interfaces.C.Strings; use Interfaces.C.Strings;
with System;
package Thinkthen_C is
   subtype Handle is System.Address;
   Null_Handle : constant Handle := System.Null_Address;
   No_Deadline : constant Interfaces.Integer_64 := -1;
   type Answer is record
      Outcome : int;
      Probability : double;
   end record with Convention => C;
   for Answer use record
      Outcome at 0 range 0 .. 31;
      Probability at 8 range 0 .. 63;
   end record;
   for Answer'Size use 128;
   type Answer_Array is array (size_t range <>) of aliased Answer with Convention => C;
   type Text_Array is array (size_t range <>) of aliased chars_ptr with Convention => C;
   type Length_Array is array (size_t range <>) of aliased size_t with Convention => C;
   function Engine_New return Handle with Import => True, Convention => C, External_Name => "thinkthen_engine_new";
   function Engine_New_With (Settings : chars_ptr) return Handle with Import => True, Convention => C, External_Name => "thinkthen_engine_new_with";
   procedure Engine_Free (E : Handle) with Import => True, Convention => C, External_Name => "thinkthen_engine_free";
   function Error_Code (E : Handle) return int with Import => True, Convention => C, External_Name => "thinkthen_error_code";
   function Error_Retryable (E : Handle) return int with Import => True, Convention => C, External_Name => "thinkthen_error_retryable";
   function Error_Message (E : Handle) return chars_ptr with Import => True, Convention => C, External_Name => "thinkthen_error_message";
   function Error_Facts_JSON (E : Handle) return chars_ptr with Import => True, Convention => C, External_Name => "thinkthen_error_facts_json";
   function Token_New return Handle with Import => True, Convention => C, External_Name => "thinkthen_cancel_token_new";
   procedure Cancel (T : Handle) with Import => True, Convention => C, External_Name => "thinkthen_cancel";
   procedure Token_Free (T : Handle) with Import => True, Convention => C, External_Name => "thinkthen_cancel_token_free";
   function Decide (E : Handle; Q, Text : chars_ptr; Length : size_t; Result : access Answer) return int with Import => True, Convention => C, External_Name => "thinkthen_decide";
   function Decide_Opts (E : Handle; Q, Text : chars_ptr; Length : size_t; Deadline : Interfaces.Integer_64; T : Handle; Result : access Answer) return int with Import => True, Convention => C, External_Name => "thinkthen_decide_opts";
   function Decide_Many (E : Handle; Q : chars_ptr; Texts : System.Address; Lengths : System.Address; Count : size_t; Results : System.Address) return int with Import => True, Convention => C, External_Name => "thinkthen_decide_many";
   function Decide_Many_Opts (E : Handle; Q : chars_ptr; Texts : System.Address; Lengths : System.Address; Count : size_t; Deadline : Interfaces.Integer_64; T : Handle; Results : System.Address) return int with Import => True, Convention => C, External_Name => "thinkthen_decide_many_opts";
   function Call_JSON (E : Handle; Request : chars_ptr) return chars_ptr with Import => True, Convention => C, External_Name => "thinkthen_call";
   function Call_JSON_Opts (E : Handle; Request : chars_ptr; Deadline : Interfaces.Integer_64; T : Handle) return chars_ptr with Import => True, Convention => C, External_Name => "thinkthen_call_opts";
   function Recognize (E : Handle; Spec, Text : chars_ptr; Length : size_t; Result : access chars_ptr; Result_Length : access size_t) return int with Import => True, Convention => C, External_Name => "thinkthen_recognize";
   function Recognize_Opts (E : Handle; Spec, Text : chars_ptr; Length : size_t; Deadline : Interfaces.Integer_64; T : Handle; Result : access chars_ptr; Result_Length : access size_t) return int with Import => True, Convention => C, External_Name => "thinkthen_recognize_opts";
   function Relate (E : Handle; Spec : chars_ptr; Texts : System.Address; Lengths : System.Address; Count : size_t; Result : access chars_ptr; Result_Length : access size_t) return int with Import => True, Convention => C, External_Name => "thinkthen_relate";
   function Relate_Opts (E : Handle; Spec : chars_ptr; Texts : System.Address; Lengths : System.Address; Count : size_t; Deadline : Interfaces.Integer_64; T : Handle; Result : access chars_ptr; Result_Length : access size_t) return int with Import => True, Convention => C, External_Name => "thinkthen_relate_opts";
   procedure Free_String (Text : chars_ptr) with Import => True, Convention => C, External_Name => "thinkthen_free_string";
end Thinkthen_C;
