from .complete import Engine as _CompleteEngine
from ._calls import Result as Result, AsyncCalls as _AsyncCalls
from ._complete import Carrier as _Carrier
from ._native_results import NativeAtomicDecideValue as _NativeDecide, NativeAtomicNullableString as _NativeChoose, NativeAtomicArrayOfString as _NativeTag, NativeAtomicDouble as _NativeScore, NativeAtomicBoolean as _NativeFilter, NativeAtomicNonZeroUsize as _NativeRank, NativeFind as _NativeFind, NativeAnnotation as _NativeAnnotation, NativeAnnotatedRow as _NativeAnnotatedRow, NativeRecognition as _NativeRecognition, NativeRecognize as _NativeRecognize, NativeRelation as _NativeRelation, NativeRelatedEntityEdge as _NativeRelatedEntityEdge
"""The typed face of ``thinkthen``. It matches ``thinkthen/__init__.py``."""

import os
from typing import Any, Annotated, Generic, Iterable, Iterator, Literal, Mapping, Optional, Sequence, TypeVar, TypedDict, Union, Unpack, overload

__all__ = [
    "BackendError", "Cancelled", "CancelToken", "DeadlineError", "DefectError",
    "Call", "Result", "Completion", "CompletionReceipt", "Edge", "Engine", "Entity", "Judge", "Stream", "Tally", "LocalError", "Question", "Recognized",
    "RecognizedEntity", "Relation", "ThinkThenError", "UsageError",
    "annotate", "choose", "decide", "details", "filter",
    "find", "plan", "question", "rank", "recognize", "relate", "score", "tag",
    "usage", "FileSelection", "SourceRecord", "Located", "read_files",
]

Path = Union[str, os.PathLike[str]]
DeadlineMs = int
Spec = Union[Path, Mapping[str, Any], type]
Asked = Union[str, "Question", _Carrier, Mapping[str, Any]]
Pair = Union[tuple[str, str], Mapping[str, Any], "Entity", "RecognizedEntity"]
# A Polars or pandas Series or another Arrow column, and a Polars or pandas
# DataFrame. A pandas Series comes back as the caller's Series, with its index
# and name. This package imports neither library, so the stub names none.
Column = Any
Frame = Any
Batch = Union[Literal["max"], int, None]
QuestionKind = Literal["decide", "choose", "tag", "score", "rank", "find"]
ErrorKind = Literal["usage", "backend", "deadline", "local", "cancelled", "defect"]
# A direct Literal[...] is a typing special form, not a portable static type.
# The native parser and Python normalizer validate this input at runtime.
LabelSet = Any

class FailedReason(TypedDict):
    kind: ErrorKind
    cause: str

class Failed(TypedDict):
    failed: FailedReason

AnnotatedValue = Union[bool, str, float, list[str], None, Failed]
AnnotatedRow = dict[str, AnnotatedValue]
T = TypeVar("T")

class SourceRecord:
    @property
    def record(self) -> str: ...
    @property
    def file(self) -> str: ...
    @property
    def first_line(self) -> int: ...
    @property
    def last_line(self) -> int: ...

class Located(Generic[T]):
    @property
    def source(self) -> SourceRecord: ...
    @property
    def value(self) -> T: ...

class FileSelection(Iterable[SourceRecord]):
    @property
    def paths(self) -> tuple[str, ...]: ...
    @property
    def unit(self) -> Literal["line", "window", "file"]: ...
    @property
    def window(self) -> int | None: ...
    def __iter__(self) -> Iterator[SourceRecord]: ...

def read_files(path_or_paths: Path | Iterable[Path], *, unit: Literal["line", "window", "file"] = ..., window: int | None = ...) -> FileSelection: ...

Facts = Mapping[str, Any]

class Call(Generic[T]):
    @property
    def value(self) -> T: ...
    @property
    def probability(self) -> Any: ...
    @property
    def facts(self) -> Facts: ...
    @property
    def details(self) -> tuple[Mapping[str, Any], ...]: ...

class Tally:
    def __init__(self) -> None: ...
    @property
    def facts(self) -> Facts: ...

class Stream(Generic[T], Iterator[T]):
    def __iter__(self) -> Stream[T]: ...
    def __next__(self) -> T: ...
    def close(self) -> None: ...
    def __enter__(self) -> Stream[T]: ...
    def __exit__(self, *ignored: Any) -> None: ...
    @property
    def facts(self) -> Optional[Facts]: ...

class Judge(Generic[T]):
    @overload
    def __call__(self, value: FileSelection, *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[list[Located[T]]]: ...
    @overload
    def __call__(self, value: str, *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[T]: ...
    @overload
    def __call__(self, value: Iterator[str], *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Stream[T]: ...
    @overload
    def __call__(self, value: Iterable[str] | Column, *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[list[T] | Column]: ...

class Completion:
    @property
    def outcome(self) -> Literal["succeeded", "failed", "panicked"]: ...
    @property
    def facts(self) -> Optional[Facts]: ...
    @property
    def details(self) -> Optional[tuple[Mapping[str, Any], ...]]: ...
    @property
    def kind(self) -> Optional[ErrorKind]: ...
    @property
    def message(self) -> Optional[str]: ...
    @property
    def retryable(self) -> Optional[bool]: ...

class CompletionReceipt:
    @property
    def done(self) -> bool: ...
    def result(self, timeout: Optional[float] = ...) -> Completion: ...

class ThinkThenError(Exception):
    kind: ErrorKind
    retryable: bool
    facts: Optional[Facts]
    details: Optional[tuple[Mapping[str, Any], ...]]

class UsageError(ThinkThenError): ...
class BackendError(ThinkThenError): ...
class LocalError(ThinkThenError): ...
class DeadlineError(ThinkThenError): ...
class DefectError(ThinkThenError): ...
class Cancelled(KeyboardInterrupt, ThinkThenError):
    completion: CompletionReceipt

class CancelToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

class Question:
    @property
    def kind(self) -> QuestionKind: ...

class Entity:
    def __init__(self, name: str, kind: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str: ...

class Edge:
    @property
    def relation(self) -> str: ...
    @property
    def source(self) -> Entity: ...
    @property
    def target(self) -> Entity: ...
    @property
    def probability(self) -> float: ...
    @property
    def either(self) -> bool: ...

class RecognizedEntity:
    @property
    def text(self) -> str: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def strength(self) -> float: ...

class Relation:
    @property
    def relation(self) -> str: ...
    @property
    def source(self) -> RecognizedEntity: ...
    @property
    def target(self) -> RecognizedEntity: ...
    @property
    def probability(self) -> float: ...
    @property
    def either(self) -> bool: ...

class Recognized:
    @property
    def entities(self) -> list[RecognizedEntity]: ...
    @property
    def relations(self) -> Optional[list[Relation]]: ...

def question(
    *,
    decide: Optional[str] = ...,
    choose: Optional[str] = ...,
    score: Optional[str] = ...,
    tag: Optional[str] = ...,
    threshold: Union[float, str, tuple[float, float], None] = ...,
    options: Union[LabelSet, None] = ...,
    labels: Union[LabelSet, None] = ...,
    levels: Union[LabelSet, None] = ...,
    true: Optional[str] = ...,
    false: Optional[str] = ...,
    model: Optional[str] = ...,
    file: Optional[Path] = ...,
) -> Question: ...

class JudgeKeywords(TypedDict, total=False):
    threshold: Union[float, str, tuple[float, float]]
    true: str
    false: str
    options: LabelSet
    levels: LabelSet
    labels: LabelSet
    model: str
    batch: Union[Literal["max"], int]
    context: str
    probability: bool
    tally: Tally

class CallKeywords(JudgeKeywords, total=False):
    details: bool
    deadline_ms: int
    token: CancelToken

class Engine:
    @property
    def asyncio(self) -> _AsyncCalls: ...
    def close(self) -> None: ...
    def __enter__(self) -> Engine: ...
    def __exit__(self, *args: Any) -> None: ...
    async def __aenter__(self) -> Engine: ...
    async def __aexit__(self, *args: Any) -> None: ...
    @property
    def complete(self) -> _CompleteEngine: ...
    def __init__(
        self,
        *,
        backend: Optional[str] = ...,
        base_url: Optional[str] = ...,
        model: Optional[str] = ...,
        throttle: Optional[int] = ...,
        batch: Batch = ...,
        max_requests: Optional[int] = ...,
        max_requests_total: Optional[int] = ...,
        max_request_bytes: Optional[int] = ...,
        cache: Union[Path, bool, None] = ...,
        timeout: Optional[int] = ...,
        max_retries: Optional[int] = ...,
        record: Union[str, Path, None] = ...,
        replay: Union[str, Path, None] = ...,
        profile: Union[str, Path, None] = ...,
    ) -> None: ...
    @overload
    def decide(self, question: Asked, text: str, *, details: Literal[True], **keywords: Any) -> Result[_NativeDecide]: ...
    @overload
    def decide(self, question: _Carrier | Mapping[str, Any], text: Any, **keywords: Any) -> Result[Any]: ...
    @overload
    def decide(self, question: Asked, text: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeDecide]]: ...
    @overload
    def decide(self, question: Asked, text: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[Optional[bool]]]: ...
    @overload
    def decide(self, question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[Optional[bool]]: ...
    @overload
    def decide(self, question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Result[Optional[bool]]: ...
    @overload
    def decide(self, question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Result[list[Optional[bool]]]: ...
    @overload
    def decide(self, question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Result[list[Optional[bool]]]: ...
    @overload
    def decide(self, question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Result[Column] | Call[Column]: ...
    @overload
    def choose(self, question: Asked, text: str, *, details: Literal[True], **keywords: Any) -> Result[_NativeChoose]: ...
    @overload
    def choose(self, question: _Carrier | Mapping[str, Any], text: Any, **keywords: Any) -> Result[Any]: ...
    @overload
    def choose(self, question: Asked, text: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeChoose]]: ...
    @overload
    def choose(self, question: Asked, text: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[Optional[str]]]: ...
    @overload
    def choose(self, question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[Optional[str]]: ...
    @overload
    def choose(self, question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Result[Optional[str]]: ...
    @overload
    def choose(self, question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Result[list[Optional[str]]]: ...
    @overload
    def choose(self, question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Result[list[Optional[str]]]: ...
    @overload
    def choose(self, question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Result[Column] | Call[Column]: ...
    @overload
    def score(self, question: Asked, text: str, *, details: Literal[True], **keywords: Any) -> Result[_NativeScore]: ...
    @overload
    def score(self, question: _Carrier | Mapping[str, Any], text: Any, **keywords: Any) -> Result[Any]: ...
    @overload
    def score(self, question: Asked, text: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeScore]]: ...
    @overload
    def score(self, question: Asked, text: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[float]]: ...
    @overload
    def score(self, question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[float]: ...
    @overload
    def score(self, question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Result[float]: ...
    @overload
    def score(self, question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Result[list[float]]: ...
    @overload
    def score(self, question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Result[list[float]]: ...
    @overload
    def score(self, question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Result[Column] | Call[Column]: ...
    @overload
    def tag(self, question: Asked, text: str, *, details: Literal[True], **keywords: Any) -> Result[_NativeTag]: ...
    @overload
    def tag(self, question: _Carrier | Mapping[str, Any], text: Any, **keywords: Any) -> Result[Any]: ...
    @overload
    def tag(self, question: Asked, text: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeTag]]: ...
    @overload
    def tag(self, question: Asked, text: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[list[str]]]: ...
    @overload
    def tag(self, question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[list[str]]: ...
    @overload
    def tag(self, question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Result[list[str]]: ...
    @overload
    def tag(self, question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Result[list[list[str]]]: ...
    @overload
    def tag(self, question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Result[list[list[str]]]: ...
    @overload
    def tag(self, question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Result[Column] | Call[Column]: ...
    def details(self, question: Asked, text: str, *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[dict[str, Any]]: ...
    @overload
    def filter(self, question: Asked, records: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeFilter]]: ...
    @overload
    def filter(self, question: Asked, records: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[str]]: ...
    @overload
    def filter(self, question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[str]: ...
    @overload
    def filter(self, question: Asked, records: Iterable[str], **keywords: Unpack[CallKeywords]) -> Result[list[str]] | Stream[str]: ...
    def plan(self, judge: Judge[Any], records: Iterable[str] | Column) -> dict[str, Any]: ...
    @overload
    def rank(self, question: Asked, records: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeRank]]: ...
    @overload
    def rank(self, question: Asked, records: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[dict[str, Any]]]: ...
    @overload
    def rank(self, question: Asked, records: Iterable[str], *, top: Optional[int] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Result[list[dict[str, Any]]]: ...
    @overload
    def find(self, question: Asked, units: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeFind]]: ...
    @overload
    def find(self, question: Asked, units: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[Optional[dict[str, Any]]]: ...
    @overload
    def find(self, question: Asked, units: Iterable[str], *, none: bool = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Result[Optional[dict[str, Any]]]: ...
    @overload
    def annotate(self, questions: Spec, records: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeAnnotation]]: ...
    @overload
    def annotate(self, questions: Spec, records: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[_NativeAnnotatedRow]]: ...
    @overload
    def annotate(self, questions: Spec, records: Iterable[str], *, on: None = ..., batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Result[list[AnnotatedRow]]: ...
    @overload
    def annotate(self, questions: Spec, records: Frame, *, on: str, batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[Frame]: ...
    @overload
    def recognize(self, text: str, ask: Any = ..., **keywords: Any) -> Result[Any]: ...
    @overload
    def recognize(self, text: FileSelection, ask: Optional[Spec] = ..., *, details: Literal[True], **keywords: Any) -> Result[list[_NativeRecognition]]: ...
    @overload
    def recognize(self, text: FileSelection, ask: Optional[Spec] = ..., *, details: Literal[False] = ..., **keywords: Any) -> Result[list[_NativeRecognize]]: ...
    @overload
    def recognize(self, text: Union[str, Frame], ask: Optional[Spec] = ..., *, kinds: Union[LabelSet, None] = ..., relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., relation_threshold: Optional[float] = ..., on: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ..., descriptions: Optional[Mapping[str, Any]] = ..., instructions: Optional[str] = ..., entity_definition: Optional[str] = ...) -> Call[Union[Recognized, Frame]]: ...
    @overload
    def relate(self, entities: FileSelection, ask: Optional[Spec] = ..., *, details: Literal[True], **keywords: Any) -> Result[list[_NativeRelation]]: ...
    @overload
    def relate(self, entities: FileSelection, ask: Optional[Spec] = ..., *, details: Literal[False] = ..., **keywords: Any) -> Result[list[list[_NativeRelatedEntityEdge]]]: ...
    @overload
    def relate(self, entities: Iterable[Pair], ask: Optional[Spec] = ..., *, relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Result[list[Edge]]: ...
    def usage(self) -> dict[str, int]: ...

@overload
def decide(question: Asked, text: str, *, details: Literal[True], **keywords: Any) -> Result[_NativeDecide]: ...
@overload
def decide(question: _Carrier | Mapping[str, Any], text: Any, **keywords: Any) -> Result[Any]: ...
@overload
def decide(question: Asked, text: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeDecide]]: ...
@overload
def decide(question: Asked, text: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[Optional[bool]]]: ...
@overload
def decide(question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[Optional[bool]]: ...
@overload
def decide(question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Result[Optional[bool]]: ...
@overload
def decide(question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Result[list[Optional[bool]]]: ...
@overload
def decide(question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Result[list[Optional[bool]]]: ...
@overload
def decide(question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Result[Column] | Call[Column]: ...
@overload
def choose(question: Asked, text: str, *, details: Literal[True], **keywords: Any) -> Result[_NativeChoose]: ...
@overload
def choose(question: _Carrier | Mapping[str, Any], text: Any, **keywords: Any) -> Result[Any]: ...
@overload
def choose(question: Asked, text: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeChoose]]: ...
@overload
def choose(question: Asked, text: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[Optional[str]]]: ...
@overload
def choose(question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[Optional[str]]: ...
@overload
def choose(question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Result[Optional[str]]: ...
@overload
def choose(question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Result[list[Optional[str]]]: ...
@overload
def choose(question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Result[list[Optional[str]]]: ...
@overload
def choose(question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Result[Column] | Call[Column]: ...
@overload
def score(question: Asked, text: str, *, details: Literal[True], **keywords: Any) -> Result[_NativeScore]: ...
@overload
def score(question: _Carrier | Mapping[str, Any], text: Any, **keywords: Any) -> Result[Any]: ...
@overload
def score(question: Asked, text: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeScore]]: ...
@overload
def score(question: Asked, text: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[float]]: ...
@overload
def score(question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[float]: ...
@overload
def score(question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Result[float]: ...
@overload
def score(question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Result[list[float]]: ...
@overload
def score(question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Result[list[float]]: ...
@overload
def score(question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Result[Column] | Call[Column]: ...
@overload
def tag(question: Asked, text: str, *, details: Literal[True], **keywords: Any) -> Result[_NativeTag]: ...
@overload
def tag(question: _Carrier | Mapping[str, Any], text: Any, **keywords: Any) -> Result[Any]: ...
@overload
def tag(question: Asked, text: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeTag]]: ...
@overload
def tag(question: Asked, text: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[list[str]]]: ...
@overload
def tag(question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[list[str]]: ...
@overload
def tag(question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Result[list[str]]: ...
@overload
def tag(question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Result[list[list[str]]]: ...
@overload
def tag(question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Result[list[list[str]]]: ...
@overload
def tag(question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Result[Column] | Call[Column]: ...
def details(question: Asked, text: str, *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[dict[str, Any]]: ...
@overload
def filter(question: Asked, records: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeFilter]]: ...
@overload
def filter(question: Asked, records: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[str]]: ...
@overload
def filter(question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[str]: ...
@overload
def filter(question: Asked, records: Iterable[str], **keywords: Unpack[CallKeywords]) -> Result[list[str]] | Stream[str]: ...
def plan(judge: Judge[Any], records: Iterable[str] | Column) -> dict[str, Any]: ...
@overload
def rank(question: Asked, records: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeRank]]: ...
@overload
def rank(question: Asked, records: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[dict[str, Any]]]: ...
@overload
def rank(question: Asked, records: Iterable[str], *, top: Optional[int] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Result[list[dict[str, Any]]]: ...
@overload
def find(question: Asked, units: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeFind]]: ...
@overload
def find(question: Asked, units: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[Optional[dict[str, Any]]]: ...
@overload
def find(question: Asked, units: Iterable[str], *, none: bool = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Result[Optional[dict[str, Any]]]: ...
@overload
def annotate(questions: Spec, records: FileSelection, *, details: Literal[True], **keywords: Any) -> Result[list[_NativeAnnotation]]: ...
@overload
def annotate(questions: Spec, records: FileSelection, *, details: Literal[False] = ..., **keywords: Any) -> Result[list[_NativeAnnotatedRow]]: ...
@overload
def annotate(questions: Spec, records: Iterable[str], *, on: None = ..., batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Result[list[AnnotatedRow]]: ...
@overload
def annotate(questions: Spec, records: Frame, *, on: str, batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[Frame]: ...
@overload
def recognize(text: str, ask: Any = ..., **keywords: Any) -> Result[Any]: ...
@overload
def recognize(text: FileSelection, ask: Optional[Spec] = ..., *, details: Literal[True], **keywords: Any) -> Result[list[_NativeRecognition]]: ...
@overload
def recognize(text: FileSelection, ask: Optional[Spec] = ..., *, details: Literal[False] = ..., **keywords: Any) -> Result[list[_NativeRecognize]]: ...
@overload
def recognize(text: Union[str, Frame], ask: Optional[Spec] = ..., *, kinds: Union[LabelSet, None] = ..., relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., relation_threshold: Optional[float] = ..., on: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ..., descriptions: Optional[Mapping[str, Any]] = ..., instructions: Optional[str] = ..., entity_definition: Optional[str] = ...) -> Call[Union[Recognized, Frame]]: ...
@overload
def relate(entities: FileSelection, ask: Optional[Spec] = ..., *, details: Literal[True], **keywords: Any) -> Result[list[_NativeRelation]]: ...
@overload
def relate(entities: FileSelection, ask: Optional[Spec] = ..., *, details: Literal[False] = ..., **keywords: Any) -> Result[list[list[_NativeRelatedEntityEdge]]]: ...
@overload
def relate(entities: Iterable[Pair], ask: Optional[Spec] = ..., *, relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Result[list[Edge]]: ...
def usage() -> dict[str, int]: ...
