"""The typed face of ``thinkthen``. It matches ``thinkthen/__init__.py``."""

import os
from typing import Any, Annotated, Generic, Iterable, Iterator, Literal, Mapping, Optional, Sequence, TypeVar, TypedDict, Union, Unpack, overload

__all__ = [
    "BackendError", "Cancelled", "CancelToken", "DeadlineError", "DefectError",
    "Call", "Completion", "CompletionReceipt", "Edge", "Engine", "Entity", "Judge", "Stream", "Tally", "LocalError", "Question", "Recognized",
    "RecognizedEntity", "Relation", "ThinkThenError", "UsageError",
    "annotate", "choose", "decide", "details", "filter",
    "find", "plan", "question", "rank", "recognize", "relate", "score", "tag",
    "usage",
]

Path = Union[str, os.PathLike[str]]
DeadlineMs = int
Spec = Union[Path, Mapping[str, Any], type]
Asked = Union[str, "Question"]
Pair = Union[tuple[str, str], Mapping[str, Any], "Entity", "RecognizedEntity"]
# A Polars or pandas Series or another Arrow column, and a Polars or pandas
# DataFrame. A pandas Series comes back as the caller's Series, with its index
# and name. This package imports neither library, so the stub names none.
Column = Any
Frame = Any
Batch = Union[Literal["max"], int, None]
QuestionKind = Literal["decide", "choose", "tag", "score", "rank", "find"]
ErrorKind = Literal["usage", "backend", "deadline", "local", "cancelled", "defect"]
# A direct Literal[...] is a typing special form, not a portable static type.
# The native parser and Python normalizer validate this input at runtime.
LabelSet = Any

class FailedReason(TypedDict):
    kind: ErrorKind
    cause: str

class Failed(TypedDict):
    failed: FailedReason

AnnotatedValue = Union[bool, str, float, list[str], None, Failed]
AnnotatedRow = dict[str, AnnotatedValue]
T = TypeVar("T")

Facts = Mapping[str, Any]

class Call(Generic[T]):
    @property
    def value(self) -> T: ...
    @property
    def probability(self) -> Any: ...
    @property
    def facts(self) -> Facts: ...
    @property
    def details(self) -> tuple[Mapping[str, Any], ...]: ...

class Tally:
    def __init__(self) -> None: ...
    @property
    def facts(self) -> Facts: ...

class Stream(Generic[T], Iterator[T]):
    def __iter__(self) -> Stream[T]: ...
    def __next__(self) -> T: ...
    def close(self) -> None: ...
    def __enter__(self) -> Stream[T]: ...
    def __exit__(self, *ignored: Any) -> None: ...
    @property
    def facts(self) -> Optional[Facts]: ...

class Judge(Generic[T]):
    @overload
    def __call__(self, value: str, *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[T]: ...
    @overload
    def __call__(self, value: Iterator[str], *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Stream[T]: ...
    @overload
    def __call__(self, value: Iterable[str] | Column, *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[list[T] | Column]: ...

class Completion:
    @property
    def outcome(self) -> Literal["succeeded", "failed", "panicked"]: ...
    @property
    def facts(self) -> Optional[Facts]: ...
    @property
    def details(self) -> Optional[tuple[Mapping[str, Any], ...]]: ...
    @property
    def kind(self) -> Optional[ErrorKind]: ...
    @property
    def message(self) -> Optional[str]: ...
    @property
    def retryable(self) -> Optional[bool]: ...

class CompletionReceipt:
    @property
    def done(self) -> bool: ...
    def result(self, timeout: Optional[float] = ...) -> Completion: ...

class ThinkThenError(Exception):
    kind: ErrorKind
    retryable: bool
    facts: Optional[Facts]
    details: Optional[tuple[Mapping[str, Any], ...]]

class UsageError(ThinkThenError): ...
class BackendError(ThinkThenError): ...
class LocalError(ThinkThenError): ...
class DeadlineError(ThinkThenError): ...
class DefectError(ThinkThenError): ...
class Cancelled(KeyboardInterrupt, ThinkThenError):
    completion: CompletionReceipt

class CancelToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

class Question:
    @property
    def kind(self) -> QuestionKind: ...

class Entity:
    def __init__(self, name: str, kind: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str: ...

class Edge:
    @property
    def relation(self) -> str: ...
    @property
    def source(self) -> Entity: ...
    @property
    def target(self) -> Entity: ...
    @property
    def probability(self) -> float: ...
    @property
    def either(self) -> bool: ...

class RecognizedEntity:
    @property
    def text(self) -> str: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def strength(self) -> float: ...

class Relation:
    @property
    def relation(self) -> str: ...
    @property
    def source(self) -> RecognizedEntity: ...
    @property
    def target(self) -> RecognizedEntity: ...
    @property
    def probability(self) -> float: ...
    @property
    def either(self) -> bool: ...

class Recognized:
    @property
    def entities(self) -> list[RecognizedEntity]: ...
    @property
    def relations(self) -> Optional[list[Relation]]: ...

def question(
    *,
    decide: Optional[str] = ...,
    choose: Optional[str] = ...,
    score: Optional[str] = ...,
    tag: Optional[str] = ...,
    threshold: Union[float, str, tuple[float, float], None] = ...,
    options: Union[LabelSet, None] = ...,
    labels: Union[LabelSet, None] = ...,
    levels: Union[LabelSet, None] = ...,
    true: Optional[str] = ...,
    false: Optional[str] = ...,
    model: Optional[str] = ...,
    file: Optional[Path] = ...,
) -> Question: ...

class JudgeKeywords(TypedDict, total=False):
    threshold: Union[float, str, tuple[float, float]]
    true: str
    false: str
    options: LabelSet
    levels: LabelSet
    labels: LabelSet
    model: str
    batch: Union[Literal["max"], int]
    context: str
    probability: bool
    tally: Tally

class CallKeywords(JudgeKeywords, total=False):
    deadline_ms: int
    token: CancelToken

class Engine:
    def __init__(
        self,
        *,
        base_url: Optional[str] = ...,
        model: Optional[str] = ...,
        throttle: Optional[int] = ...,
        batch: Batch = ...,
        max_requests: Optional[int] = ...,
        max_requests_total: Optional[int] = ...,
        max_request_bytes: Optional[int] = ...,
        cache: Union[Path, bool, None] = ...,
        timeout: Optional[int] = ...,
        max_retries: Optional[int] = ...,
        record: Union[str, Path, None] = ...,
        replay: Union[str, Path, None] = ...,
        profile: Union[str, Path, None] = ...,
    ) -> None: ...
    @overload
    def decide(self, question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[Optional[bool]]: ...
    @overload
    def decide(self, question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Call[Optional[bool]]: ...
    @overload
    def decide(self, question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Stream[Optional[bool]]: ...
    @overload
    def decide(self, question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Call[list[Optional[bool]]]: ...
    @overload
    def decide(self, question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Call[Column]: ...
    @overload
    def choose(self, question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[Optional[str]]: ...
    @overload
    def choose(self, question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Call[Optional[str]]: ...
    @overload
    def choose(self, question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Stream[Optional[str]]: ...
    @overload
    def choose(self, question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Call[list[Optional[str]]]: ...
    @overload
    def choose(self, question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Call[Column]: ...
    @overload
    def score(self, question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[float]: ...
    @overload
    def score(self, question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Call[float]: ...
    @overload
    def score(self, question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Stream[float]: ...
    @overload
    def score(self, question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Call[list[float]]: ...
    @overload
    def score(self, question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Call[Column]: ...
    @overload
    def tag(self, question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[list[str]]: ...
    @overload
    def tag(self, question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Call[list[str]]: ...
    @overload
    def tag(self, question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Stream[list[str]]: ...
    @overload
    def tag(self, question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Call[list[list[str]]]: ...
    @overload
    def tag(self, question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Call[Column]: ...
    def details(self, question: Asked, text: str, *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[dict[str, Any]]: ...
    @overload
    def filter(self, question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[str]: ...
    @overload
    def filter(self, question: Asked, records: Iterable[str], **keywords: Unpack[CallKeywords]) -> Call[list[str]] | Stream[str]: ...
    def plan(self, judge: Judge[Any], records: Iterable[str] | Column) -> dict[str, Any]: ...
    def rank(self, question: Asked, records: Iterable[str], *, top: Optional[int] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[list[dict[str, Any]]]: ...
    def find(self, question: Asked, units: Iterable[str], *, none: bool = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[Optional[dict[str, Any]]]: ...
    @overload
    def annotate(self, questions: Spec, records: Iterable[str], *, on: None = ..., batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[list[AnnotatedRow]]: ...
    @overload
    def annotate(self, questions: Spec, records: Frame, *, on: str, batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[Frame]: ...
    def recognize(self, text: Union[str, Frame], ask: Optional[Spec] = ..., *, kinds: Union[LabelSet, None] = ..., relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., relation_threshold: Optional[float] = ..., on: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ..., descriptions: Optional[Mapping[str, Any]] = ...) -> Call[Union[Recognized, Frame]]: ...
    def relate(self, entities: Iterable[Pair], ask: Optional[Spec] = ..., *, relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[list[Edge]]: ...
    def usage(self) -> dict[str, int]: ...

@overload
def decide(question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[Optional[bool]]: ...
@overload
def decide(question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Call[Optional[bool]]: ...
@overload
def decide(question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Stream[Optional[bool]]: ...
@overload
def decide(question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Call[list[Optional[bool]]]: ...
@overload
def decide(question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Call[Column]: ...
@overload
def choose(question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[Optional[str]]: ...
@overload
def choose(question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Call[Optional[str]]: ...
@overload
def choose(question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Stream[Optional[str]]: ...
@overload
def choose(question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Call[list[Optional[str]]]: ...
@overload
def choose(question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Call[Column]: ...
@overload
def score(question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[float]: ...
@overload
def score(question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Call[float]: ...
@overload
def score(question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Stream[float]: ...
@overload
def score(question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Call[list[float]]: ...
@overload
def score(question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Call[Column]: ...
@overload
def tag(question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[list[str]]: ...
@overload
def tag(question: Asked, text: str, **keywords: Unpack[CallKeywords]) -> Call[list[str]]: ...
@overload
def tag(question: Asked, text: Iterator[str], **keywords: Unpack[CallKeywords]) -> Stream[list[str]]: ...
@overload
def tag(question: Asked, text: Iterable[str], **keywords: Unpack[CallKeywords]) -> Call[list[list[str]]]: ...
@overload
def tag(question: Asked, text: Column, **keywords: Unpack[CallKeywords]) -> Call[Column]: ...
def details(question: Asked, text: str, *, deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[dict[str, Any]]: ...
@overload
def filter(question: Asked, **keywords: Unpack[JudgeKeywords]) -> Judge[str]: ...
@overload
def filter(question: Asked, records: Iterable[str], **keywords: Unpack[CallKeywords]) -> Call[list[str]] | Stream[str]: ...
def plan(judge: Judge[Any], records: Iterable[str] | Column) -> dict[str, Any]: ...
def rank(question: Asked, records: Iterable[str], *, top: Optional[int] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[list[dict[str, Any]]]: ...
def find(question: Asked, units: Iterable[str], *, none: bool = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[Optional[dict[str, Any]]]: ...
@overload
def annotate(questions: Spec, records: Iterable[str], *, on: None = ..., batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[list[AnnotatedRow]]: ...
@overload
def annotate(questions: Spec, records: Frame, *, on: str, batch: Batch = ..., context: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[Frame]: ...
def recognize(text: Union[str, Frame], ask: Optional[Spec] = ..., *, kinds: Union[LabelSet, None] = ..., relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., relation_threshold: Optional[float] = ..., on: Optional[str] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ..., descriptions: Optional[Mapping[str, Any]] = ...) -> Call[Union[Recognized, Frame]]: ...
def relate(entities: Iterable[Pair], ask: Optional[Spec] = ..., *, relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., deadline_ms: DeadlineMs = ..., token: Optional[CancelToken] = ...) -> Call[list[Edge]]: ...
def usage() -> dict[str, int]: ...
