"""The typed face of ``thinkthen``. It matches ``thinkthen/__init__.py``."""

import os
from typing import Any, Annotated, Generic, Iterable, Literal, Mapping, Optional, Sequence, TypeVar, TypedDict, Union, overload

__all__ = [
    "BackendError", "Cancelled", "CancelToken", "DeadlineError", "DefectError",
    "Call", "Completion", "CompletionReceipt", "Edge", "Engine", "Entity", "Facts", "LocalError", "Question", "Recognized",
    "RecognizedEntity", "Relation", "ThinkThenError", "UsageError",
    "annotate", "choose", "choose_many", "decide", "decide_many", "details", "filter",
    "find", "question", "rank", "recognize", "relate", "score", "score_many", "tag", "tag_many",
    "usage",
]

Path = Union[str, os.PathLike[str]]
Deadline = Optional[float]
Spec = Union[Path, Mapping[str, Any], type]
Asked = Union[str, "Question"]
Pair = Union[tuple[str, str], Mapping[str, Any], "Entity", "RecognizedEntity"]
# A Polars or pandas Series or another Arrow column, and a Polars or pandas
# DataFrame. A pandas Series comes back as the caller's Series, with its index
# and name. This package imports neither library, so the stub names none.
Column = Any
Frame = Any
Batch = Union[Literal["max"], int, None]
QuestionKind = Literal["decide", "choose", "tag", "score", "rank", "find"]
ErrorKind = Literal["usage", "backend", "deadline", "local", "cancelled", "defect"]
# A direct Literal[...] is a typing special form, not a portable static type.
# The native parser and Python normalizer validate this input at runtime.
LabelSet = Any

class FailedReason(TypedDict):
    kind: ErrorKind
    cause: str

class Failed(TypedDict):
    failed: FailedReason

AnnotatedValue = Union[bool, str, float, list[str], None, Failed]
AnnotatedRow = dict[str, AnnotatedValue]
T = TypeVar("T")

class Facts:
    @property
    def records(self) -> int: ...
    @property
    def requests_sent(self) -> int: ...
    @property
    def cache_answers(self) -> int: ...
    @property
    def input_tokens(self) -> Optional[int]: ...
    @property
    def output_tokens(self) -> Optional[int]: ...
    @property
    def seconds(self) -> float: ...
    @property
    def model(self) -> Optional[str]: ...

class Call(Generic[T]):
    @property
    def value(self) -> T: ...
    @property
    def facts(self) -> Facts: ...
    @property
    def details(self) -> tuple[Mapping[str, Any], ...]: ...

class Completion:
    @property
    def outcome(self) -> Literal["succeeded", "failed", "panicked"]: ...
    @property
    def facts(self) -> Optional[Facts]: ...
    @property
    def details(self) -> Optional[tuple[Mapping[str, Any], ...]]: ...
    @property
    def kind(self) -> Optional[ErrorKind]: ...
    @property
    def message(self) -> Optional[str]: ...
    @property
    def retryable(self) -> Optional[bool]: ...

class CompletionReceipt:
    @property
    def done(self) -> bool: ...
    def result(self, timeout: Optional[float] = ...) -> Completion: ...

class ThinkThenError(Exception):
    kind: ErrorKind
    retryable: bool
    facts: Optional[Facts]
    details: Optional[tuple[Mapping[str, Any], ...]]

class UsageError(ThinkThenError): ...
class BackendError(ThinkThenError): ...
class LocalError(ThinkThenError): ...
class DeadlineError(ThinkThenError): ...
class DefectError(ThinkThenError): ...
class Cancelled(KeyboardInterrupt, ThinkThenError):
    completion: CompletionReceipt

class CancelToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

class Question:
    @property
    def kind(self) -> QuestionKind: ...

class Entity:
    def __init__(self, name: str, kind: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str: ...

class Edge:
    @property
    def relation(self) -> str: ...
    @property
    def source(self) -> Entity: ...
    @property
    def target(self) -> Entity: ...
    @property
    def probability(self) -> float: ...

class RecognizedEntity:
    @property
    def text(self) -> str: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def strength(self) -> float: ...

class Relation:
    @property
    def relation(self) -> str: ...
    @property
    def source(self) -> RecognizedEntity: ...
    @property
    def target(self) -> RecognizedEntity: ...
    @property
    def probability(self) -> float: ...

class Recognized:
    @property
    def entities(self) -> list[RecognizedEntity]: ...
    @property
    def relations(self) -> Optional[list[Relation]]: ...

def question(
    *,
    decide: Optional[str] = ...,
    choose: Optional[str] = ...,
    score: Optional[str] = ...,
    tag: Optional[str] = ...,
    threshold: Union[float, str, tuple[float, float], None] = ...,
    options: Union[LabelSet, None] = ...,
    labels: Union[LabelSet, None] = ...,
    levels: Union[LabelSet, None] = ...,
    true_: Optional[str] = ...,
    false_: Optional[str] = ...,
    model: Optional[str] = ...,
    file: Optional[Path] = ...,
    descriptions: Optional[Mapping[str, Any]] = ...,
) -> Question: ...

class Engine:
    def __init__(
        self,
        *,
        base_url: Optional[str] = ...,
        model: Optional[str] = ...,
        throttle: Optional[int] = ...,
        batch: Batch = ...,
        max_requests: Optional[int] = ...,
        max_request_bytes: Optional[int] = ...,
        cache: Union[Path, bool, None] = ...,
        timeout: Optional[int] = ...,
        max_retries: Optional[int] = ...,
        record: Union[str, Path, None] = ...,
        replay: Union[str, Path, None] = ...,
        profile: Union[str, Path, None] = ...,
    ) -> None: ...
    def decide(self, question: Asked, text: Union[str, Column], *, batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Union[Optional[bool], Column]]: ...
    def decide_many(self, question: Asked, records: Union[Iterable[str], Column], *, batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Union[list[Optional[bool]], Column]]: ...
    def choose(self, question: Asked, text: Union[str, Column], *, options: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Union[Optional[str], Column]]: ...
    def choose_many(self, question: Asked, records: Iterable[str], *, options: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[Optional[str]]]: ...
    def score(self, question: Asked, text: Union[str, Column], *, levels: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Union[float, Column]]: ...
    def score_many(self, question: Asked, records: Iterable[str], *, levels: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[float]]: ...
    def tag(self, question: Asked, text: Union[str, Column], *, labels: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Union[list[str], Column]]: ...
    def tag_many(self, question: Asked, records: Iterable[str], *, labels: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[list[str]]]: ...
    def details(self, question: Asked, text: str, *, deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[dict[str, Any]]: ...
    def filter(self, question: Asked, records: Iterable[str], *, batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[str]]: ...
    def rank(self, question: Asked, records: Iterable[str], *, top: Optional[int] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[dict[str, Any]]]: ...
    def find(self, question: Asked, units: Iterable[str], *, none: bool = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Optional[dict[str, Any]]]: ...
    @overload
    def annotate(self, questions: Spec, records: Iterable[str], *, on: None = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[AnnotatedRow]]: ...
    @overload
    def annotate(self, questions: Spec, records: Frame, *, on: str, batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Frame]: ...
    def recognize(self, text: Union[str, Frame], ask: Optional[Spec] = ..., *, kinds: Union[LabelSet, None] = ..., relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., relation_threshold: Optional[float] = ..., on: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ..., descriptions: Optional[Mapping[str, Any]] = ...) -> Call[Union[Recognized, Frame]]: ...
    def relate(self, entities: Iterable[Pair], ask: Optional[Spec] = ..., *, relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[Edge]]: ...
    def usage(self) -> dict[str, int]: ...

def decide(question: Asked, text: Union[str, Column], *, batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Union[Optional[bool], Column]]: ...
def decide_many(question: Asked, records: Union[Iterable[str], Column], *, batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Union[list[Optional[bool]], Column]]: ...
def choose(question: Asked, text: Union[str, Column], *, options: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Union[Optional[str], Column]]: ...
def choose_many(question: Asked, records: Iterable[str], *, options: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[Optional[str]]]: ...
def score(question: Asked, text: Union[str, Column], *, levels: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Union[float, Column]]: ...
def score_many(question: Asked, records: Iterable[str], *, levels: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[float]]: ...
def tag(question: Asked, text: Union[str, Column], *, labels: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Union[list[str], Column]]: ...
def tag_many(question: Asked, records: Iterable[str], *, labels: Union[LabelSet, None] = ..., descriptions: Optional[Mapping[str, Any]] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[list[str]]]: ...
def details(question: Asked, text: str, *, deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[dict[str, Any]]: ...
def filter(question: Asked, records: Iterable[str], *, batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[str]]: ...
def rank(question: Asked, records: Iterable[str], *, top: Optional[int] = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[dict[str, Any]]]: ...
def find(question: Asked, units: Iterable[str], *, none: bool = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Optional[dict[str, Any]]]: ...
@overload
def annotate(questions: Spec, records: Iterable[str], *, on: None = ..., batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[AnnotatedRow]]: ...
@overload
def annotate(questions: Spec, records: Frame, *, on: str, batch: Batch = ..., context: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[Frame]: ...
def recognize(text: Union[str, Frame], ask: Optional[Spec] = ..., *, kinds: Union[LabelSet, None] = ..., relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., relation_threshold: Optional[float] = ..., on: Optional[str] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ..., descriptions: Optional[Mapping[str, Any]] = ...) -> Call[Union[Recognized, Frame]]: ...
def relate(entities: Iterable[Pair], ask: Optional[Spec] = ..., *, relations: Optional[Mapping[str, tuple[str, str]]] = ..., either: Optional[Iterable[str]] = ..., threshold: Optional[float] = ..., deadline: Deadline = ..., token: Optional[CancelToken] = ...) -> Call[list[Edge]]: ...
def usage() -> dict[str, int]: ...
