from typing import Any, Generic, TypeVar
from ._native_results import _NativeResult, NativeFacts, NativeSessionPacketTerminal
T = TypeVar('T')
class Result(Generic[T]):
    results: tuple[_NativeResult, ...]
    terminal: NativeSessionPacketTerminal
    function: str
    scalar: bool
    detailed: bool
    @property
    def value(self) -> T: ...
    @property
    def probability(self) -> Any: ...
    @property
    def details(self) -> tuple[_NativeResult, ...]: ...
    @property
    def facts(self) -> NativeFacts | None: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...
class AsyncCalls:
    async def decide(self, question: Any, value: Any, **controls: Any) -> Result[Any]: ...
    async def choose(self, question: Any, value: Any, **controls: Any) -> Result[Any]: ...
    async def tag(self, question: Any, value: Any, **controls: Any) -> Result[Any]: ...
    async def score(self, question: Any, value: Any, **controls: Any) -> Result[Any]: ...
    async def filter(self, question: Any, value: Any, **controls: Any) -> Result[Any]: ...
    async def rank(self, question: Any, value: Any, **controls: Any) -> Result[Any]: ...
    async def find(self, question: Any, value: Any, **controls: Any) -> Result[Any]: ...
    async def annotate(self, question: Any, value: Any, **controls: Any) -> Result[Any]: ...
    async def recognize(self, text: Any, ask: Any = ..., **controls: Any) -> Result[Any]: ...
    async def relate(self, entities: Any, ask: Any = ..., **controls: Any) -> Result[Any]: ...
