from dataclasses import dataclass
from typing import Generic, Iterator, Literal, TypeVar
from ._complete import *
from . import CancelToken
R = TypeVar('R')
@dataclass(frozen=True, kw_only=True)
class QuestionSource:
    role: Literal['atomic','dynamic','rank','set','find','recognize','relate']
    body: Carrier | JsonValue | None = ...
    path: str | None = ...
    name: str | None = ...
    reference: str | None = ...
    none: bool = ...
    raw: str | None = ...
@dataclass(frozen=True, kw_only=True)
class Image:
    media: Literal['image/png','image/jpeg']
    data: bytes
@dataclass(frozen=True, kw_only=True)
class Item:
    value: JsonValue = ...
    text: bool = ...
    images: tuple[Image, ...] = ...
    context: JsonValue | Absent = ...
    options: tuple[tuple[str, Description | Absent], ...] | Absent = ...
    image_only: bool = ...
@dataclass(frozen=True)
class Records:
    items: tuple[Item, ...]
@dataclass(frozen=True, kw_only=True)
class Files:
    paths: tuple[str, ...]
    unit: Literal['line','window','file'] = ...
    window: int | Absent = ...
    media: Literal['text','image'] = ...
    jsonl: bool = ...
@dataclass(frozen=True)
class Completed(Generic[R]):
    results: tuple[R, ...]
    facts: Facts
    ordinals: tuple[int | None, ...]
    inputs: tuple[NativeInput, ...]
@dataclass(frozen=True)
class BatchRow(Generic[R]):
    result: R
    ordinal: int
    input: NativeInput
class Batch(Iterator[BatchRow[R]]):
    facts: Facts | None
    def __iter__(self) -> Batch[R]: ...
    def __next__(self) -> BatchRow[R]: ...
    def close(self) -> None: ...
    def cancel(self) -> None: ...
    def __enter__(self) -> Batch[R]: ...
    def __exit__(self, *args: object) -> None: ...
class Engine:
    def __init__(self, **settings: object) -> None: ...
    def decide(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Completed[DecideResult]: ...
    def choose(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Completed[ChooseResult]: ...
    def tag(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Completed[TagResult]: ...
    def score(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Completed[ScoreResult]: ...
    def filter(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Completed[FilterResult]: ...
    def rank(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Completed[RankResult]: ...
    def find(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Completed[FindResult]: ...
    def annotate(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Completed[AnnotateResult]: ...
    def recognize(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Completed[RecognizeResult]: ...
    def relate(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Completed[RelateResult]: ...
    def decide_batch(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Batch[DecideResult]: ...
    def choose_batch(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Batch[ChooseResult]: ...
    def tag_batch(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Batch[TagResult]: ...
    def score_batch(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Batch[ScoreResult]: ...
    def filter_batch(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Batch[FilterResult]: ...
    def annotate_batch(self, question:QuestionSource, source:Records|Files, *, token:CancelToken|None=..., deadline_ms:int|None=..., attempts:bool=..., context:str|None=...) -> Batch[AnnotateResult]: ...
