from typing import Generic, Iterator, Literal, TypeVar
from dataclasses import dataclass
from . import Engine as OrdinaryEngine, CancelToken
from . import complete as c
R = TypeVar('R')
@dataclass(frozen=True)
class FrameCompleted(Generic[R]):
    native: c.Completed[R]
    frame: object
    source: object
    positions: tuple[int | None, ...]
    index: object
    name: object
    @property
    def facts(self) -> c.Facts: ...
    @property
    def results(self) -> tuple[R, ...]: ...
    @property
    def inputs(self) -> tuple[c.NativeInput, ...]: ...
class FrameBatch(Iterator[c.BatchRow[R]], Generic[R]):
    native: c.Batch[R]
    source: object
    positions: tuple[int, ...] | None
    index: object
    name: object
    @property
    def facts(self) -> c.Facts | None: ...
    def __iter__(self) -> FrameBatch[R]: ...
    def __next__(self) -> c.BatchRow[R]: ...
    def position(self, row: c.BatchRow[R]) -> int: ...
    def close(self) -> None: ...
    def cancel(self) -> None: ...
    def __enter__(self) -> FrameBatch[R]: ...
    def __exit__(self, *args: object) -> None: ...
class Engine:
    def __init__(self, *, engine: OrdinaryEngine | c.Engine | None = ..., library: Literal['pandas','polars'] = ..., **settings: object) -> None: ...
    def decide(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameCompleted[c.DecideResult]: ...
    def decide_batch(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameBatch[c.DecideResult]: ...
    def choose(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameCompleted[c.ChooseResult]: ...
    def choose_batch(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameBatch[c.ChooseResult]: ...
    def tag(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameCompleted[c.TagResult]: ...
    def tag_batch(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameBatch[c.TagResult]: ...
    def score(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameCompleted[c.ScoreResult]: ...
    def score_batch(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameBatch[c.ScoreResult]: ...
    def filter(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameCompleted[c.FilterResult]: ...
    def filter_batch(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameBatch[c.FilterResult]: ...
    def rank(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameCompleted[c.RankResult]: ...
    def find(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameCompleted[c.FindResult]: ...
    def annotate(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameCompleted[c.AnnotateResult]: ...
    def annotate_batch(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameBatch[c.AnnotateResult]: ...
    def recognize(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameCompleted[c.RecognizeResult]: ...
    def relate(self, question: c.QuestionSource, source: object, *, on: str | None = ..., token: CancelToken | None = ..., deadline_ms: int | None = ..., attempts: bool = ..., context: str | None = ...) -> FrameCompleted[c.RelateResult]: ...
