from typing import Any
from . import Engine
from ._pandas_calls import PandasResult
from .frames import FrameCompleted

class ThinkThenAccessor:
    def __init__(self, series: Any) -> None: ...
    def decide(self, question: Any, *, engine: Engine | None = ..., **keywords: Any) -> PandasResult: ...
    def choose(self, question: Any, *, engine: Engine | None = ..., **keywords: Any) -> PandasResult: ...
    def score(self, question: Any, *, engine: Engine | None = ..., **keywords: Any) -> PandasResult: ...
    def tag(self, question: Any, *, engine: Engine | None = ..., **keywords: Any) -> PandasResult: ...
    def filter(self, question: Any, *, engine: Engine | None = ..., **keywords: Any) -> PandasResult: ...
    def rank(self, question: Any, *, engine: Engine | None = ..., **keywords: Any) -> PandasResult: ...
    def find(self, question: Any, *, engine: Engine | None = ..., **keywords: Any) -> PandasResult: ...
    def annotate(self, questions: Any, *, engine: Engine | None = ..., **keywords: Any) -> PandasResult: ...
    def recognize(self, ask: Any = ..., *, engine: Engine | None = ..., **keywords: Any) -> PandasResult: ...
    def relate(self, ask: Any = ..., *, engine: Engine | None = ..., **keywords: Any) -> PandasResult: ...
    def complete(self, *, engine: Engine | None = ...) -> CompleteAccessor: ...

class CompleteAccessor:
    def decide(self, question: Any, **controls: Any) -> FrameCompleted: ...
    def choose(self, question: Any, **controls: Any) -> FrameCompleted: ...
    def score(self, question: Any, **controls: Any) -> FrameCompleted: ...
    def tag(self, question: Any, **controls: Any) -> FrameCompleted: ...
    def filter(self, question: Any, **controls: Any) -> FrameCompleted: ...
    def rank(self, question: Any, **controls: Any) -> FrameCompleted: ...
    def find(self, question: Any, **controls: Any) -> FrameCompleted: ...
    def annotate(self, question: Any, **controls: Any) -> FrameCompleted: ...
    def recognize(self, question: Any, **controls: Any) -> FrameCompleted: ...
    def relate(self, question: Any, **controls: Any) -> FrameCompleted: ...
