from typing import Any
from polars import Series
from . import Engine
from ._polars_calls import PolarsResult
class ThinkThenNamespace:
    def __init__(self, series: Series) -> None: ...
    def decide(self, question: Any, *, engine: Engine | None = ..., **controls: Any) -> PolarsResult: ...
    def choose(self, question: Any, *, engine: Engine | None = ..., **controls: Any) -> PolarsResult: ...
    def score(self, question: Any, *, engine: Engine | None = ..., **controls: Any) -> PolarsResult: ...
    def tag(self, question: Any, *, engine: Engine | None = ..., **controls: Any) -> PolarsResult: ...
    def filter(self, question: Any, *, engine: Engine | None = ..., **controls: Any) -> PolarsResult: ...
    def rank(self, question: Any, *, engine: Engine | None = ..., **controls: Any) -> PolarsResult: ...
    def find(self, question: Any, *, engine: Engine | None = ..., **controls: Any) -> PolarsResult: ...
    def annotate(self, question: Any, *, engine: Engine | None = ..., **controls: Any) -> PolarsResult: ...
    def recognize(self, ask: Any = ..., *, engine: Engine | None = ..., **controls: Any) -> PolarsResult: ...
    def relate(self, ask: Any = ..., *, engine: Engine | None = ..., **controls: Any) -> PolarsResult: ...
