# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib thinkthen, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_thinkthen_wrappers", use_symbols = TRUE, package_name = "thinkthen")

#' @usage NULL
#' @useDynLib thinkthen, .registration = TRUE
NULL

#' Build a question through the one file grammar, any verb, any threshold.
tt_question_grammared <- function(body) .Call(wrap__tt_question_grammared, body)

#' Build a recognize ask through the question file's own section grammar.
tt_recognize_grammared <- function(spec) .Call(wrap__tt_recognize_grammared, spec)

#' Build a relate ask through the question file's own section grammar.
tt_relate_grammared <- function(spec) .Call(wrap__tt_relate_grammared, spec)

#' `recognize` over a column: one crossing, every record in input order.
#'
#' Each record becomes the plain data for a data frame of names — text,
#' kind, and the offsets in R's own string indexing, so `substr(text,
#' start, end)` is the name — plus the relations when any were found.
tt_recognize_column <- function(ask, texts, deadline) .Call(wrap__tt_recognize_column, ask, texts, deadline)

#' `relate` over records: every record crosses at once; the answer is the
#' plain data for a data frame of edges, with the kind fields when a rule
#' named kinds.
tt_relate_records <- function(ask, records, deadline) .Call(wrap__tt_relate_records, ask, records, deadline)

#' `decide` over a column: one crossing, every judgment in input order.
tt_decide_column <- function(question, records, deadline) .Call(wrap__tt_decide_column, question, records, deadline)

#' One `decide` of one evidence.
tt_decide_one <- function(question, evidence, deadline) .Call(wrap__tt_decide_one, question, evidence, deadline)

#' One `choose`: the winning option, or NULL when unsure.
tt_choose_one <- function(question, evidence, deadline) .Call(wrap__tt_choose_one, question, evidence, deadline)

#' One `score`: the weighted position and the nearest level.
tt_score_one <- function(question, evidence, deadline) .Call(wrap__tt_score_one, question, evidence, deadline)

#' One `tag`: the labels that held, in the question's order.
tt_tag_one <- function(question, evidence, deadline) .Call(wrap__tt_tag_one, question, evidence, deadline)

#' `find` over units: the winner's place, one-based, and its probability.
tt_find_one <- function(question, units, deadline) .Call(wrap__tt_find_one, question, units, deadline)

#' `filter` over records: the places, one-based, whose evidence held.
tt_filter_places <- function(question, records, deadline) .Call(wrap__tt_filter_places, question, records, deadline)

#' `rank` over records: places in rank order with their probabilities.
tt_rank_all <- function(question, records, deadline) .Call(wrap__tt_rank_all, question, records, deadline)

#' `annotate` over records from a question set file: each row a named list
#' in the set's own order, each field typed by its question's verb.
tt_annotate_file <- function(path, records, deadline) .Call(wrap__tt_annotate_file, path, records, deadline)

#' The question set's names and kinds, in the set's own name order, so the
#' R half types each answer column by its question rather than by the first
#' answer it happens to see. A name carrying a NUL byte (the file grammar
#' can spell one) refuses here: R strings cannot hold one, and the
#' conversion would abort the process.
tt_annotate_kinds <- function(path) .Call(wrap__tt_annotate_kinds, path)

#' The audit view of one judgment, with the logical requests' digests
#' (0053) and the failed-question count (0054).
tt_details_one <- function(question, evidence, deadline) .Call(wrap__tt_details_one, question, evidence, deadline)

#' The process counters.
tt_usage_counters <- function() .Call(wrap__tt_usage_counters)

#' Whether R holds a pending interrupt, for the R half's own checks before
#' and after a call.
tt_interrupt_pending <- function() .Call(wrap__tt_interrupt_pending)

#' Deliver R's own interrupt for real, from pure R-side code where no Rust
#' frame owns anything. The synthetic condition this replaces was raised
#' through `stop()`, so a user's `options(error = ...)` hook fired on an
#' interrupt - the third review's probe - and R continued instead of
#' halting. This is the real check, unguarded: the jump it makes is R's
#' own interrupt delivery, caught by `tryCatch(interrupt = ...)` exactly
#' as a genuine Ctrl-C is. Called only after the guarded check reported a
#' pending interrupt and the call's cleanup ran; if the poll finds nothing
#' left to deliver, it returns and the R half's fallback stops the call.
tt_raise_interrupt <- function() invisible(.Call(wrap__tt_raise_interrupt))

#' Stop the call in flight, when an interrupt jumped out of its frame.
tt_cancel_active <- function() .Call(wrap__tt_cancel_active)

#' The digest of a question value, for the audit pages.
tt_question_digest <- function(question) .Call(wrap__tt_question_digest, question)

#' The kind and members of a question value, for printing.
tt_question_parts <- function(question) .Call(wrap__tt_question_parts, question)

# nolint end
