# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib thinkthen, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_thinkthen_wrappers", use_symbols = TRUE, package_name = "thinkthen")

#' @usage NULL
#' @useDynLib thinkthen, .registration = TRUE
NULL

#' Check a question file and name its kind.
tt_question_check <- function(body) .Call(wrap__tt_question_check, body)

tt_source_files <- function(question, selection, deadline) .Call(wrap__tt_source_files, question, selection, deadline)

#' Read a question file under the crate's one 1 MiB cap.
tt_question_file <- function(path) .Call(wrap__tt_question_file, path)

#' Validate keyword settings with the shared core grammar before a send.
tt_settings_check <- function(body, kind) .Call(wrap__tt_settings_check, body, kind)

tt_decide_column <- function(question, records, positions, deadline, batch, context, completion) .Call(wrap__tt_decide_column, question, records, positions, deadline, batch, context, completion)

#' Preview the same packed request bodies without reading a key or sending.
tt_plan_column <- function(question, records, batch, context) .Call(wrap__tt_plan_column, question, records, batch, context)

tt_column <- function(question, records, positions, deadline, batch, context, completion) .Call(wrap__tt_column, question, records, positions, deadline, batch, context, completion)

tt_filter_places <- function(question, records, deadline, batch, context, completion) .Call(wrap__tt_filter_places, question, records, deadline, batch, context, completion)

tt_rank_all <- function(question, records, deadline, batch, context, completion) .Call(wrap__tt_rank_all, question, records, deadline, batch, context, completion)

tt_find_one <- function(question, units, none, deadline, completion) .Call(wrap__tt_find_one, question, units, none, deadline, completion)

tt_annotate_file <- function(path, records, taken, deadline, batch, completion) .Call(wrap__tt_annotate_file, path, records, taken, deadline, batch, completion)

tt_details_one <- function(question, evidence, deadline, completion) .Call(wrap__tt_details_one, question, evidence, deadline, completion)

tt_usage_counters <- function() .Call(wrap__tt_usage_counters)

tt_interrupt_pending <- function() .Call(wrap__tt_interrupt_pending)

tt_recognize_column <- function(spec, path, texts, positions, deadline, completion) .Call(wrap__tt_recognize_column, spec, path, texts, positions, deadline, completion)

tt_relate_frame <- function(spec, path, names, kinds, deadline, completion) .Call(wrap__tt_relate_frame, spec, path, names, kinds, deadline, completion)

tt_completion_new <- function() .Call(wrap__tt_completion_new)

tt_completion_claim <- function(value) .Call(wrap__tt_completion_claim, value)

tt_completion_read_native <- function(value) .Call(wrap__tt_completion_read_native, value)

tt_completion_settle_early <- function(value, kind) .Call(wrap__tt_completion_settle_early, value, kind)

tt_engine_set <- function(base_url, model, throttle, max_requests, max_requests_total, max_request_bytes, cache, timeout, max_retries, record, replay, profile, batch, backend, refresh_cache) .Call(wrap__tt_engine_set, base_url, model, throttle, max_requests, max_requests_total, max_request_bytes, cache, timeout, max_retries, record, replay, profile, batch, backend, refresh_cache)

tt_complete_error_native <- function(error) .Call(wrap__tt_complete_error_native, error)

tt_complete_native <- function(request, deadline, completion) .Call(wrap__tt_complete_native, request, deadline, completion)

tt_complete_batch_start <- function(request, deadline) .Call(wrap__tt_complete_batch_start, request, deadline)

tt_complete_batch_pull <- function(batch) .Call(wrap__tt_complete_batch_pull, batch)

tt_complete_batch_poll <- function(batch, advance) .Call(wrap__tt_complete_batch_poll, batch, advance)

tt_complete_batch_close <- function(batch) .Call(wrap__tt_complete_batch_close, batch)

tt_complete_batch_cancel <- function(batch) .Call(wrap__tt_complete_batch_cancel, batch)

# nolint end
