using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;
namespace ThinkThen;
internal static partial class NativeComplete {
 internal static string String(StringV1 v) { if(v.len>int.MaxValue || v.data==IntPtr.Zero&&v.len!=0) throw new InvalidOperationException("invalid native string extent");byte[] b=new byte[checked((int)v.len)];if(b.Length!=0)Marshal.Copy(v.data,b,0,b.Length);return new UTF8Encoding(false,true).GetString(b); }
 internal static IReadOnlyList<T> Array<C,T>(IntPtr data,nuint count,Func<C,T> copy) where C:struct {if(count>int.MaxValue||data==IntPtr.Zero&&count!=0)throw new InvalidOperationException("invalid native array extent");T[] outValues=new T[checked((int)count)];int stride=Marshal.SizeOf<C>();for(int i=0;i<outValues.Length;i++)outValues[i]=copy(Marshal.PtrToStructure<C>(IntPtr.Add(data,checked(i*stride))));return outValues;}
 internal static Optional<T> Opt<T>(int present,Func<T> copy)=>present==0?default:Optional.Some(copy());
 internal static Probability ReadProbability(ProbabilityV1 v)=>new(String(v.name),v.probability);
 internal static Content ReadContent(ContentV1 v) {if(v.kind==0)return new(ContentKind.Absent,"",default);if(v.kind==1)return new(ContentKind.Text,String(v.data),default);if(v.kind!=2)throw new InvalidOperationException("invalid native content kind");using var json=JsonDocument.Parse(String(v.data));return new(ContentKind.Json,"",json.RootElement.Clone());}
 internal static ImageView ReadImageView(ImageViewV1 v) {byte[] bytes=new byte[checked((int)v.bytes_len)];if(bytes.Length!=0)Marshal.Copy(v.bytes,bytes,0,bytes.Length);return new((Media)(v.media-1),bytes,v.width,v.height,Opt(v.filename.present,()=>String(v.filename.value)));}
 internal static DecideValue ReadDecideValue(DecideValueV1 v)=>new((ValueKind)v.kind,v.kind==1&&v.data.boolean!=0,v.kind==2?Optional.Some(ReadContent(v.data.authored)):default);
 internal static AtomicAnswer ReadAtomicAnswer(AnswerV1 v) {
  IReadOnlyList<Probability> p=System.Array.Empty<Probability>();Optional<double> yes=default,confidence=default;Optional<string> pick=default,level=default;
  AtomicKind kind=v.kind switch {1=>AtomicKind.YesNo,2=>AtomicKind.Choice,3=>AtomicKind.Tag,4=>AtomicKind.Score,5=>AtomicKind.Find,_=>throw new InvalidOperationException("invalid native atomic kind")};
  if(v.kind==1)yes=Optional.Some(v.data.probability);
  else if(v.kind==2||v.kind==5){var a=v.kind==2?v.data.choice:v.data.find;pick=Optional.Some(String(a.pick));p=Array<ProbabilityV1,Probability>(a.probabilities.data,a.probabilities.len,ReadProbability);confidence=Opt(a.confidence.present,()=>a.confidence.value);}
  else if(v.kind==3)p=Array<ProbabilityV1,Probability>(v.data.tag.data,v.data.tag.len,ReadProbability);
  else if(v.kind==4){level=Optional.Some(String(v.data.score.level));p=Array<ProbabilityV1,Probability>(v.data.score.probabilities.data,v.data.score.probabilities.len,ReadProbability);confidence=Opt(v.data.score.confidence.present,()=>v.data.score.confidence.value);}
  else throw new InvalidOperationException("invalid native atomic kind");return new(kind,yes,pick,level,p,confidence);
 }
 internal static MemberValue ReadMemberValue(MemberValueV1 v)=>new((Function)(v.kind-1),v.kind==1?Optional.Some(ReadDecideValue(v.data.decide)):default,v.kind==2?Opt(v.data.choose.present,()=>String(v.data.choose.value)):default,v.kind==3?Optional.Some(Array<StringV1,string>(v.data.tag.data,v.data.tag.len,String)):default,v.kind==4?Optional.Some(v.data.score):default);
 internal static AnnotationMember ReadAnnotationMember(MemberV1 v)=>new(String(v.name),new Digest(String(v.request)),ReadQuestion(v.question),(MemberState)(v.state-1),v.state==1?Optional.Some(ReadMemberSuccess(v.data.success)):default,v.state==2?Optional.Some(ReadMemberFailure(v.data.failure)):default);
 internal static RelationAnswer ReadRelationAnswer(RelationAnswerV1 v)=>new(String(v.relation),String(v.reads),(RelationMethod)(v.method-1),(Direction)(v.direction-1),ReadEndpoint(v.source),Opt(v.target.present,()=>ReadEndpoint(v.target.value)),new Digest(String(v.request)),(MemberState)(v.state-1),v.state==1?Optional.Some(ReadRelationSuccess(v.data.success)):default,v.state==2?Optional.Some(ReadMemberFailure(v.data.failure)):default);
 internal static ObservationIdentity ReadObservationIdentity(ObservationIdentityV1 v)=>new((IdentityKind)(v.kind-1),v.kind==1?Optional.Some(new ObservationId(String(v.data.observation_id))):default,v.kind==2?Optional.Some(new FailureId(String(v.data.failure_id))):default);
 internal static ObservedProbabilities ReadObservedProbabilities(ObservedProbabilitiesV1 v)=>new(v.kind==1?Optional.Some(v.data.yes):default,v.kind==2?Optional.Some(Array<ProbabilityV1,Probability>(v.data.named.data,v.data.named.len,ReadProbability)):default);
 internal static ObservationSuccess ReadObservationSuccess(ObservationSuccessV1 v)=>new(new AnswerId(String(v.answer_id)),v.observation_id.len!=0?Optional.Some(new ObservationId(String(v.observation_id))):default,ReadMemberValue(v.value),ReadObservedProbabilities(v.probabilities),Opt(v.confidence.present,()=>v.confidence.value));
 internal static Question ReadQuestion(QuestionViewV1 v)=>new((Function)(v.kind-1),ReadContent(v.text),Opt(v.yes.present,()=>ReadContent(v.yes.value)),Opt(v.no.present,()=>ReadContent(v.no.value)),Array<ChoiceV1,Choice>(v.choices.data,v.choices.len,ReadChoice),ReadRule(v.threshold),ReadRule(v.relation_threshold),Opt(v.model.present,()=>String(v.model.value)),Opt(v.profile.present,()=>String(v.profile.value)),Opt(v.batch.present,()=>checked((ulong)v.batch.value)),v.batch_max!=0,v.none!=0,Array<StringV1,string>(v.on.data,v.on.len,String),Array<QuestionMemberV1,QuestionMember>(v.members.data,v.members.len,m=>new(String(m.name),ReadQuestion(Marshal.PtrToStructure<QuestionViewV1>(m.question)))),Array<ChoiceV1,Choice>(v.kinds.data,v.kinds.len,ReadChoice),Array<RelationV1,Relation>(v.relations.data,v.relations.len,ReadRelation),Opt(v.name_pointer.present,()=>String(v.name_pointer.value)),Opt(v.kind_pointer.present,()=>String(v.kind_pointer.value)));
 internal static QuestionObservation ReadQuestionObservation(QuestionObservationV1 v)=>new((ulong)v.index,Opt(v.member.present,()=>String(v.member.value)),Opt(v.stage.present,()=>(Stage)(v.stage.value-1)),(ulong)v.position,new Digest(String(v.question_sha256)),String(v.model),String(v.url),Array<StringV1,Digest>(v.requests.data,v.requests.len,s=>new Digest(String(s))),v.requests_sent,v.cached!=0,(ulong)v.failed_questions,Opt(v.usage.present,()=>ReadTokenUsage(v.usage.value)),Array<QuestionSourceV1,QuestionSource>(v.question_sources.data,v.question_sources.len,ReadQuestionSource),(MemberState)(v.state-1),v.state==1?Optional.Some(ReadObservationSuccess(v.data.success)):default,v.state==2?Optional.Some(ReadMemberFailure(v.data.failure)):default);
 internal static ObservationEvent ReadObservationEvent(ObservationV1 v)=>new((EventKind)(v.kind-1),v.kind==1?Optional.Some(ReadQuestionObservation(v.data.question)):default,v.kind==2?Optional.Some(ReadRowObservation(v.data.row)):default);
 internal static RowObservation ReadRowObservation(RowObservationV1 v)=>new((ulong)v.index,new RowValue((Function)(v.function-1),
v.function==1?Optional.Some(ReadDecideRow(v.data.decide)):default,v.function==2?Optional.Some(ReadChooseRow(v.data.choose)):default,v.function==3?Optional.Some(ReadTagRow(v.data.tag)):default,v.function==4?Optional.Some(ReadScoreRow(v.data.score)):default,v.function==5?Optional.Some(ReadFilterRow(v.data.filter)):default,v.function==6?Optional.Some(ReadRankRow(v.data.rank)):default,v.function==7?Optional.Some(ReadFindRow(v.data.find)):default,v.function==8?Optional.Some(ReadAnnotateRow(v.data.annotate)):default,v.function==9?Optional.Some(ReadRecognizeRow(v.data.recognize)):default,v.function==10?Optional.Some(ReadRelateRow(v.data.relate)):default));
}
