namespace ThinkThen;
internal static partial class NativeComplete {
 internal static RecognizeAnswer ReadRecognizeAnswer(RecognizeAnswerV1 v) => new(Array<PieceV1,Piece>(v.pieces.data,v.pieces.len,x=>ReadPiece(x)),Array<NameV1,NameSpan>(v.names.data,v.names.len,x=>ReadNameSpan(x)),Array<PairV1,PairSpan>(v.pairs.data,v.pairs.len,x=>ReadPairSpan(x)));
 internal static Endpoint ReadEndpoint(EndpointV1 v) => new(String(v.name),String(v.kind));
 internal static Edge ReadEdge(EdgeV1 v) => new(String(v.relation),ReadEndpoint(v.source),ReadEndpoint(v.target),(double)v.probability,v.either!=0);
 internal static RelationSuccess ReadRelationSuccess(RelationSuccessV1 v) => new(new AnswerId(String(v.answer_id)),(double)v.probability,v.accepted!=0);
 internal static TokenUsage ReadTokenUsage(UsageV1 v) => new(checked((ulong)v.input_tokens),checked((ulong)v.output_tokens));
 internal static QuestionSource ReadQuestionSource(QuestionSourceV1 v) => new((Origin)checked((int)v.origin-1),String(v.answered_by));
 internal static ProfileWarning ReadProfileWarning(ProfileWarningV1 v) => new(String(v.tuned_for),String(v.running));
 internal static BatchSetting ReadBatchSetting(BatchV1 v) => new((BatchKind)checked((int)v.kind-1),checked((ulong)v.records));
 internal static BatchWarning ReadBatchWarning(BatchWarningV1 v) => new(ReadBatchSetting(v.tuned_for),ReadBatchSetting(v.running));
 internal static Attempt ReadAttempt(AttemptV1 v) => new(checked((ulong)v.ordinal),new Digest(String(v.request_sha256)),checked((ulong)v.wall_ms),(AttemptOutcome)checked((int)v.outcome-1),new SdkRequestId(String(v.sdk_request_id)),Opt(v.status.present,()=>checked((ulong)v.status.value)),Opt(v.server_ms.present,()=>checked((ulong)v.server_ms.value)),Opt(v.request_id.present,()=>String(v.request_id.value)));
 internal static Meta ReadMeta(MetaV1 v) => new(String(v.tool),Opt(v.question_sha256.present,()=>new Digest(String(v.question_sha256.value))),Opt(v.questions_sha256.present,()=>new Digest(String(v.questions_sha256.value))),String(v.url),String(v.model),Opt(v.usage.present,()=>ReadTokenUsage(v.usage.value)),checked((ulong)v.requests_sent),v.cached!=0,Array<StringV1,Digest>(v.requests.data,v.requests.len,x=>new Digest(String(x))),checked((ulong)v.failed_questions),Opt(v.profile_warning.present,()=>ReadProfileWarning(v.profile_warning.value)),Opt(v.batch_setting.present,()=>ReadBatchSetting(v.batch_setting.value)),Opt(v.batch_warning.present,()=>ReadBatchWarning(v.batch_warning.value)),Opt(v.context_sha256.present,()=>new Digest(String(v.context_sha256.value))),Opt(v.attempts.present,()=>Array<AttemptV1,Attempt>(v.attempts.value.data,v.attempts.value.len,x=>ReadAttempt(x))),Opt(v.origin.present,()=>(Origin)checked((int)v.origin.value-1)),Array<QuestionSourceV1,QuestionSource>(v.question_sources.data,v.question_sources.len,x=>ReadQuestionSource(x)),Array<ObservationIdentityV1,ObservationIdentity>(v.observations.data,v.observations.len,x=>ReadObservationIdentity(x)),Opt(v.answered_by.present,()=>String(v.answered_by.value)));
 internal static CallFacts ReadCallFacts(FactsV1 v) => new(new CallId(String(v.call_id)),checked((ulong)v.cache_answers),Opt(v.estimated_cost_usd.present,()=>String(v.estimated_cost_usd.value)),Opt(v.input_tokens.present,()=>checked((ulong)v.input_tokens.value)),Opt(v.model.present,()=>String(v.model.value)),Opt(v.output_tokens.present,()=>checked((ulong)v.output_tokens.value)),checked((ulong)v.records),checked((ulong)v.requests_sent),(double)v.seconds,Opt(v.command_ms.present,()=>checked((ulong)v.command_ms.value)));
 internal static Stopped ReadStopped(StoppedV1 v) => new(Opt(v.at.present,()=>checked((ulong)v.at.value)),(StopCause)checked((int)v.cause-1),Opt(v.status.present,()=>checked((ulong)v.status.value)),v.retryable!=0);
 internal static CommonRow ReadCommonRow(RowV1 v) => new(new AnswerId(String(v.answer_id)),Opt(v.input.present,()=>ReadContent(v.input.value)),Opt(v.question.present,()=>ReadQuestion(v.question.value)),Opt(v.answer.present,()=>ReadAtomicAnswer(v.answer.value)),Opt(v.threshold.present,()=>ReadRule(v.threshold.value)),Opt(v.position.present,()=>ReadLocation(v.position.value)),Opt(v.input_file.present,()=>String(v.input_file.value)),ReadMeta(v.meta),Opt(v.images.present,()=>Array<ImageViewV1,ImageView>(v.images.value.data,v.images.value.len,x=>ReadImageView(x))));
 internal static DecideRow ReadDecideRow(DecideViewV1 v) => new(ReadCommonRow(v.common),ReadDecideValue(v.value));
}
