package thinkthen;
import java.lang.foreign.*;
import java.util.*;
import thinkthen.Complete.*;
import thinkthen.CompleteDetails.*;
import static thinkthen.NativeReaders0.*;
import static thinkthen.NativeReaders1.*;
import static thinkthen.NativeReaders2.*;
import thinkthen.Ids.*;
import static thinkthen.NativeLayouts.*;
import static thinkthen.NativeRead.*;
import static java.lang.foreign.ValueLayout.*;
final class NativeDetailReaders0 {
 static ReportedUsage readReportedUsage(MemorySegment v) {return new ReportedUsage(field(v,"thinkthen_reported_usage_v1","present").get(JAVA_INT,0)!=0,optional(field(v,"thinkthen_reported_usage_v1","input_tokens"), "thinkthen_optional_u64_v1", x1 -> (long)x1.get(JAVA_LONG,0)),optional(field(v,"thinkthen_reported_usage_v1","output_tokens"), "thinkthen_optional_u64_v1", x3 -> (long)x3.get(JAVA_LONG,0)));}
 static SourceDetail readSourceDetail(MemorySegment v) {return new SourceDetail(enumeration(Origin.values(),field(v,"thinkthen_source_detail_v1","origin").get(JAVA_INT,0),1),string(field(v,"thinkthen_source_detail_v1","answered_by")),optional(field(v,"thinkthen_source_detail_v1","batch_size"), "thinkthen_optional_size_v1", x7 -> (long)x7.get(JAVA_LONG,0)));}
 static InputView readInputView(MemorySegment v) {return new InputView(optional(field(v,"thinkthen_input_view_v1","original"), "thinkthen_optional_content_v1", x9 -> readContent(x9)),optional(field(v,"thinkthen_input_view_v1","position"), "thinkthen_optional_location_v1", x11 -> readLocation(x11)),optional(field(v,"thinkthen_input_view_v1","images"), "thinkthen_optional_image_views_v1", x13 -> array(x13, "thinkthen_image_views_v1", "thinkthen_image_view_v1", x14 -> readImageView(x14))));}
 static Details readDetails(MemorySegment v) {return new Details(optional(field(v,"thinkthen_details_v1","question"), "thinkthen_optional_question_v1", x16 -> readQuestion(x16)),optional(field(v,"thinkthen_details_v1","threshold"), "thinkthen_optional_rule_v1", x18 -> readRule(x18)),optional(field(v,"thinkthen_details_v1","raw_pick"), "thinkthen_optional_string_v1", x20 -> string(x20)),readReportedUsage(field(v,"thinkthen_details_v1","usage")),array(field(v,"thinkthen_details_v1","question_sources"), "thinkthen_source_details_v1", "thinkthen_source_detail_v1", x23 -> readSourceDetail(x23)),array(field(v,"thinkthen_details_v1","observations"), "thinkthen_observation_identities_v1", "thinkthen_observation_identity_v1", x25 -> readObservationIdentity(x25)),array(field(v,"thinkthen_details_v1","inputs"), "thinkthen_input_views_v1", "thinkthen_input_view_v1", x27 -> readInputView(x27)));}
 static SourceEntity readSourceEntity(MemorySegment v) {return new SourceEntity(readEntity(field(v,"thinkthen_source_entity_v1","entity")),optional(field(v,"thinkthen_source_entity_v1","position"), "thinkthen_optional_location_v1", x30 -> readLocation(x30)));}
 static SourceEntityEdge readSourceEntityEdge(MemorySegment v) {return new SourceEntityEdge(string(field(v,"thinkthen_source_entity_edge_v1","relation")),readSourceEntity(field(v,"thinkthen_source_entity_edge_v1","source")),readSourceEntity(field(v,"thinkthen_source_entity_edge_v1","target")),field(v,"thinkthen_source_entity_edge_v1","probability").get(JAVA_DOUBLE,0),field(v,"thinkthen_source_entity_edge_v1","either").get(JAVA_INT,0)!=0);}
 static SourceRecognition readSourceRecognition(MemorySegment v) {return new SourceRecognition(field(v,"thinkthen_source_recognition_v1","present").get(JAVA_INT,0)!=0,array(field(v,"thinkthen_source_recognition_v1","entities"), "thinkthen_source_entities_v1", "thinkthen_source_entity_v1", x38 -> readSourceEntity(x38)),optional(field(v,"thinkthen_source_recognition_v1","relations"), "thinkthen_optional_source_entity_edges_v1", x40 -> array(x40, "thinkthen_source_entity_edges_v1", "thinkthen_source_entity_edge_v1", x41 -> readSourceEntityEdge(x41))));}
 static SourceEndpoint readSourceEndpoint(MemorySegment v) {return new SourceEndpoint((long)field(v,"thinkthen_source_endpoint_v1","ordinal").get(JAVA_LONG,0),readEndpoint(field(v,"thinkthen_source_endpoint_v1","endpoint")),readContent(field(v,"thinkthen_source_endpoint_v1","record")),optional(field(v,"thinkthen_source_endpoint_v1","position"), "thinkthen_optional_location_v1", x46 -> readLocation(x46)));}
 static SourceEdge readSourceEdge(MemorySegment v) {return new SourceEdge(string(field(v,"thinkthen_source_edge_v1","relation")),readSourceEndpoint(field(v,"thinkthen_source_edge_v1","source")),readSourceEndpoint(field(v,"thinkthen_source_edge_v1","target")),field(v,"thinkthen_source_edge_v1","probability").get(JAVA_DOUBLE,0),field(v,"thinkthen_source_edge_v1","either").get(JAVA_INT,0)!=0);}
 static SourceRelations readSourceRelations(MemorySegment v) {return new SourceRelations(field(v,"thinkthen_source_relations_v1","present").get(JAVA_INT,0)!=0,array(field(v,"thinkthen_source_relations_v1","edges"), "thinkthen_source_edges_v1", "thinkthen_source_edge_v1", x54 -> readSourceEdge(x54)));}
 static InputProperty readInputProperty(MemorySegment v) {return new InputProperty(string(field(v,"thinkthen_input_property_v1","name")),enumeration(PropertyKind.values(),field(v,"thinkthen_input_property_v1","kind").get(JAVA_INT,0),1));}
 static InputDeclaration readInputDeclaration(MemorySegment v) {return new InputDeclaration(enumeration(DeclarationKind.values(),field(v,"thinkthen_input_declaration_v1","kind").get(JAVA_INT,0),0),array(field(v,"thinkthen_input_declaration_v1","properties"), "thinkthen_input_properties_v1", "thinkthen_input_property_v1", x59 -> readInputProperty(x59)),array(field(v,"thinkthen_input_declaration_v1","required"), "thinkthen_strings_v1", "thinkthen_string_v1", x61 -> string(x61)));}
 static QuestionAuthor readQuestionAuthor(MemorySegment v) {return new QuestionAuthor(optional(field(v,"thinkthen_question_author_v1","name"), "thinkthen_optional_string_v1", x63 -> string(x63)),optional(field(v,"thinkthen_question_author_v1","wording_version"), "thinkthen_optional_u64_v1", x65 -> (long)x65.get(JAVA_LONG,0)),readInputDeclaration(field(v,"thinkthen_question_author_v1","item_schema")),readInputDeclaration(field(v,"thinkthen_question_author_v1","context_schema")));}
}
