package thinkthen;
import java.lang.foreign.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.function.BiConsumer;
import thinkthen.Complete.*;
import thinkthen.Requests.*;
import static java.lang.foreign.ValueLayout.*;
import static thinkthen.NativeLayouts.*;
import static thinkthen.NativeRead.*;
import static thinkthen.NativeCalls.*;
final class NativeInputs implements AutoCloseable {
 final Arena arena=Arena.ofConfined();final List<MemorySegment> questions=new ArrayList<>(),images=new ArrayList<>();MemorySegment source=MemorySegment.NULL;
 MemorySegment allocate(String type){return arena.allocate(layout("thinkthen_"+type+"_v1"));}
 MemorySegment string(String value){MemorySegment s=allocate("string");byte[] b=value.getBytes(StandardCharsets.UTF_8);f(s,"string","data").set(ADDRESS,0,Door.bytes(arena,b));f(s,"string","len").set(JAVA_LONG,0,b.length);return s;}
 void copy(MemorySegment target,MemorySegment value){MemorySegment.copy(value,0,target,0,value.byteSize());}
 <T> void optional(MemorySegment target,String type,OptionalValue<T> value,BiConsumer<MemorySegment,T> write){if(value.present()){field(target,type,"present").set(JAVA_INT,0,1);write.accept(field(target,type,"value"),value.value());}}
 void content(MemorySegment target,Content c){if(c.kind()==ContentKind.ABSENT)return;f(target,"content","kind").set(JAVA_INT,0,c.kind().ordinal()+1);copy(f(target,"content","data"),string(c.kind()==ContentKind.TEXT?c.text():Json.write(c.json())));}
 void optionalContent(MemorySegment target,OptionalValue<Content> v){optional(target,"thinkthen_optional_content_v1",v,this::content);}
 void optionalString(MemorySegment target,OptionalValue<String> v){optional(target,"thinkthen_optional_string_v1",v,(t,s)->copy(t,string(s)));}
 <T> void array(MemorySegment target,String container,String element,List<T> values,BiConsumer<MemorySegment,T> write){long stride=layout("thinkthen_"+element+"_v1").byteSize();MemorySegment data=arena.allocate(Math.max(1,Math.multiplyExact(stride,values.size())),layout("thinkthen_"+element+"_v1").byteAlignment());for(int i=0;i<values.size();i++)write.accept(data.asSlice(i*stride,stride),values.get(i));f(target,container,"data").set(ADDRESS,0,data);f(target,container,"len").set(JAVA_LONG,0,values.size());}
 void strings(MemorySegment target,List<String> values){array(target,"strings","string",values,(t,s)->copy(t,string(s)));}
 void choices(MemorySegment target,List<Choice> values){array(target,"choices","choice",values,(t,c)->{copy(f(t,"choice","name"),string(c.name()));optionalContent(f(t,"choice","description"),c.description());optional(f(t,"choice","weight"),"thinkthen_optional_double_v1",c.weight(),(p,v)->p.set(JAVA_DOUBLE,0,v));});}
 void rule(MemorySegment target,Rule r){f(target,"rule","kind").set(JAVA_INT,0,r.kind().ordinal());f(target,"rule","low").set(JAVA_DOUBLE,0,r.low());f(target,"rule","high").set(JAVA_DOUBLE,0,r.high());}
 void size(MemorySegment target,OptionalValue<Long> size){optional(target,"thinkthen_optional_size_v1",size,(t,n)->{if(n<0)throw new IllegalArgumentException("negative size");t.set(JAVA_LONG,0,n);});}
 MemorySegment question(MemorySegment e,Question q){MemorySegment spec=allocate("question_spec");String type="question_spec";f(spec,type,"kind").set(JAVA_INT,0,q.kind().ordinal()+1);if(q.kind().ordinal()<7||q.text().kind()!=ContentKind.TEXT||!q.text().text().isEmpty())content(f(spec,type,"text"),q.text());optionalContent(f(spec,type,"yes"),q.yes());optionalContent(f(spec,type,"no"),q.no());choices(f(spec,type,"choices"),q.choices());rule(f(spec,type,"threshold"),q.threshold());rule(f(spec,type,"relation_threshold"),q.relationThreshold());optionalString(f(spec,type,"model"),q.model());optionalString(f(spec,type,"profile"),q.profile());size(f(spec,type,"batch"),q.batch());f(spec,type,"batch_max").set(JAVA_INT,0,q.batchMax()?1:0);f(spec,type,"none").set(JAVA_INT,0,q.none()?1:0);strings(f(spec,type,"on"),q.on());
 array(f(spec,type,"members"),"member_specs","member_spec",q.members(),(t,m)->{copy(f(t,"member_spec","name"),string(m.name()));f(t,"member_spec","question").set(ADDRESS,0,question(e,m.question()));});choices(f(spec,type,"kinds"),q.kinds());
 array(f(spec,type,"relations"),"relations","relation",q.relations(),(t,r)->{copy(f(t,"relation","name"),string(r.name()));copy(f(t,"relation","source"),string(r.source()));copy(f(t,"relation","target"),string(r.target()));optionalString(f(t,"relation","reads"),r.reads());f(t,"relation","either").set(JAVA_INT,0,r.either()?1:0);f(t,"relation","single").set(JAVA_INT,0,r.single()?1:0);});optionalString(f(spec,type,"name_pointer"),q.namePointer());optionalString(f(spec,type,"kind_pointer"),q.kindPointer());MemorySegment out=arena.allocate(ADDRESS);if(q.author().present()){MemorySegment author=allocate("question_author");author(author,q.author().value());check(e,(int)call("thinkthen_question_new_authored",e,spec,author,out));}else check(e,(int)call("thinkthen_question_new",e,spec,out));MemorySegment result=out.get(ADDRESS,0);questions.add(result);return result;
 }
 MemorySegment asked(MemorySegment e,QuestionInput q){int count=(q.question().present()?1:0)+(q.file().present()?1:0)+(q.saved().present()?1:0)+(q.named().present()?1:0)+(q.reference().present()?1:0);if(count!=1)throw new IllegalArgumentException("select exactly one question input");if(q.question().present())return question(e,q.question().value());MemorySegment out=arena.allocate(ADDRESS);int rc;if(q.file().present())rc=(int)call("thinkthen_question_load",e,string(q.file().value()),out);else if(q.saved().present())rc=(int)call("thinkthen_question_parse",e,q.role().ordinal()+1,string(q.saved().value()),out);else if(q.named().present())rc=(int)call("thinkthen_question_load_named",e,q.role().ordinal()+1,string(q.named().value()),out);else rc=(int)call("thinkthen_question_load_reference",e,q.role().ordinal()+1,string(q.reference().value()),out);check(e,rc);MemorySegment result=out.get(ADDRESS,0);questions.add(result);return result;}
 MemorySegment input(MemorySegment e,InputSource input){if(input.records().present()==input.files().present())throw new IllegalArgumentException("select exactly one input source");MemorySegment out=arena.allocate(ADDRESS);int rc;
 if(input.files().present()){FileSource files=input.files().value();MemorySegment spec=allocate("source_spec");strings(f(spec,"source_spec","paths"),files.paths());f(spec,"source_spec","unit").set(JAVA_INT,0,files.unit().ordinal()+1);f(spec,"source_spec","window").set(JAVA_LONG,0,files.window());rc=(int)call(files.imageReader()?"thinkthen_source_image_files":"thinkthen_source_files",e,spec,out);}
 else {List<RecordInput> values=input.records().value();long stride=layout("thinkthen_record_v1").byteSize();MemorySegment rows=arena.allocate(Math.max(1,Math.multiplyExact(stride,values.size())),layout("thinkthen_record_v1").byteAlignment());for(int i=0;i<values.size();i++){RecordInput r=values.get(i);MemorySegment t=rows.asSlice(i*stride,stride);optionalContent(f(t,"record","original"),r.original());optionalContent(f(t,"record","context"),r.context());choices(f(t,"record","options"),r.options());MemorySegment handles=arena.allocate(Math.max(1,r.images().size()*ADDRESS.byteSize()),ADDRESS.byteAlignment());for(int j=0;j<r.images().size();j++){ImageInput image=r.images().get(j);MemorySegment filename=allocate("optional_string");optionalString(filename,image.filename());MemorySegment handle=arena.allocate(ADDRESS);check(e,(int)call("thinkthen_image_clone",e,Door.bytes(arena,image.bytes()),(long)image.bytes().length,image.media().ordinal()+1,filename,handle));MemorySegment owned=handle.get(ADDRESS,0);images.add(owned);handles.setAtIndex(ADDRESS,j,owned);}f(f(t,"record","images"),"images","data").set(ADDRESS,0,handles);f(f(t,"record","images"),"images","len").set(JAVA_LONG,0,r.images().size());}rc=(int)call("thinkthen_source_records",e,rows,(long)values.size(),out);}
 check(e,rc);source=out.get(ADDRESS,0);return source;
 }
 MemorySegment controls(CallControls c,long deadline,MemorySegment token,String surface){MemorySegment out=allocate("controls");f(out,"controls","deadline_ms").set(JAVA_LONG,0,deadline);f(out,"controls","cancel").set(ADDRESS,0,token);optionalContent(f(out,"controls","context"),c.context());size(f(out,"controls","batch"),c.batch());f(out,"controls","batch_max").set(JAVA_INT,0,c.batchMax()?1:0);f(out,"controls","attempts").set(JAVA_INT,0,c.attempts()?1:0);copy(f(out,"controls","surface"),string(surface));return out;}
void declaration(MemorySegment target,thinkthen.CompleteDetails.InputDeclaration d){f(target,"input_declaration","kind").set(JAVA_INT,0,d.kind().ordinal());array(f(target,"input_declaration","properties"),"input_properties","input_property",d.properties(),(t,p)->{copy(f(t,"input_property","name"),string(p.name()));f(t,"input_property","kind").set(JAVA_INT,0,p.kind().ordinal()+1);});strings(f(target,"input_declaration","required"),d.required());}
 void author(MemorySegment target,thinkthen.CompleteDetails.QuestionAuthor a){optionalString(f(target,"question_author","name"),a.name());optional(f(target,"question_author","wording_version"),"thinkthen_optional_u64_v1",a.wordingVersion(),(t,n)->t.set(JAVA_LONG,0,n));declaration(f(target,"question_author","item_schema"),a.itemSchema());declaration(f(target,"question_author","context_schema"),a.contextSchema());}
 @Override public void close(){call("thinkthen_source_free",source);for(MemorySegment q:questions)call("thinkthen_question_free",q);for(MemorySegment i:images)call("thinkthen_image_free",i);arena.close();}
}
