package thinkthen;
import java.lang.foreign.*;
import java.util.*;
import java.util.function.Function;
import thinkthen.Complete.*;
import thinkthen.Ids.*;
import static java.lang.foreign.ValueLayout.*;
import static thinkthen.NativeLayouts.*;
import static thinkthen.NativeReaders0.*;
import static thinkthen.NativeReaders1.*;
import static thinkthen.NativeReaders2.*;
final class NativeRead {
 static MemorySegment f(MemorySegment v,String type,String name){return field(v,"thinkthen_"+type+"_v1",name);}
 static MemorySegment u(MemorySegment v,String type,String name){return field(f(v,type,"data"),"thinkthen_"+type+"_v1_data",name);}
 static int i(MemorySegment v){return v.get(JAVA_INT,0);}
 static long l(MemorySegment v){return v.get(JAVA_LONG,0);}
 static double d(MemorySegment v){return v.get(JAVA_DOUBLE,0);}
 static <T> T enumeration(T[] values,int v,int start){int n=v-start;if(n<0||n>=values.length)throw new IllegalStateException("invalid native discriminator");return values[n];}
 static String string(MemorySegment v){MemorySegment p=f(v,"string","data").get(ADDRESS,0);long n=l(f(v,"string","len"));if(n==0)return "";return Door.copyCounted(p,n);}
 static <T> OptionalValue<T> optional(MemorySegment v,String type,Function<MemorySegment,T> copy){return i(field(v,type,"present"))==0?OptionalValue.absent():OptionalValue.of(copy.apply(field(v,type,"value")));}
 static <T> List<T> array(MemorySegment v,String type,String element,Function<MemorySegment,T> copy){long n=l(field(v,type,"len"));if(n<0||n>Integer.MAX_VALUE)throw new IllegalStateException("invalid native array extent");if(n==0)return List.of();MemorySegment p=field(v,type,"data").get(ADDRESS,0);long stride=layout(element).byteSize();MemorySegment memory=p.reinterpret(Math.multiplyExact(n,stride));List<T> values=new ArrayList<>((int)n);for(long at=0;at<n;at++)values.add(copy.apply(memory.asSlice(at*stride,stride)));return List.copyOf(values);}
 static Content readContent(MemorySegment v){int kind=i(f(v,"content","kind"));if(kind==0)return new Content(ContentKind.ABSENT,"",null);String value=string(f(v,"content","data"));if(kind==1)return new Content(ContentKind.TEXT,value,null);if(kind==2)return new Content(ContentKind.JSON,"",Json.parse(value));throw new IllegalStateException("invalid native content kind");}
 static ImageView readImageView(MemorySegment v){long n=l(f(v,"image_view","bytes_len"));if(n<0||n>Integer.MAX_VALUE)throw new IllegalStateException("invalid native image extent");byte[] bytes=n==0?new byte[0]:f(v,"image_view","bytes").get(ADDRESS,0).reinterpret(n).toArray(JAVA_BYTE);return new ImageView(enumeration(Media.values(),i(f(v,"image_view","media")),1),bytes,Integer.toUnsignedLong(i(f(v,"image_view","width"))),Integer.toUnsignedLong(i(f(v,"image_view","height"))),optional(f(v,"image_view","filename"),"thinkthen_optional_string_v1",NativeRead::string));}
 static DecideValue readDecideValue(MemorySegment v){int kind=i(f(v,"decide_value","kind"));return new DecideValue(enumeration(ValueKind.values(),kind,0),kind==1&&i(u(v,"decide_value","boolean"))!=0,kind==2?OptionalValue.of(readContent(u(v,"decide_value","authored"))):OptionalValue.absent());}
 static List<Probability> probabilities(MemorySegment v){return array(v,"thinkthen_probabilities_v1","thinkthen_probability_v1",NativeReaders0::readProbability);}
 static AtomicAnswer readAtomicAnswer(MemorySegment v){int kind=i(f(v,"answer","kind"));OptionalValue<Double> yes=OptionalValue.absent(),confidence=OptionalValue.absent();OptionalValue<String> pick=OptionalValue.absent(),level=OptionalValue.absent();List<Probability> values=List.of();
  if(kind==1)yes=OptionalValue.of(d(u(v,"answer","probability")));
  else if(kind==2||kind==5){MemorySegment a=u(v,"answer",kind==2?"choice":"find");pick=OptionalValue.of(string(f(a,"named_answer","pick")));values=probabilities(f(a,"named_answer","probabilities"));confidence=optional(f(a,"named_answer","confidence"),"thinkthen_optional_double_v1",NativeRead::d);}
  else if(kind==3)values=probabilities(u(v,"answer","tag"));
  else if(kind==4){MemorySegment a=u(v,"answer","score");level=OptionalValue.of(string(f(a,"score_answer","level")));values=probabilities(f(a,"score_answer","probabilities"));confidence=optional(f(a,"score_answer","confidence"),"thinkthen_optional_double_v1",NativeRead::d);}
  else throw new IllegalStateException("invalid native atomic kind");return new AtomicAnswer(switch(kind){case 1->AtomicKind.YES_NO;case 2->AtomicKind.CHOICE;case 3->AtomicKind.TAG;case 4->AtomicKind.SCORE;case 5->AtomicKind.FIND;default->throw new IllegalStateException("invalid native atomic kind");},yes,pick,level,values,confidence);
 }
 static MemberValue readMemberValue(MemorySegment v){int kind=i(f(v,"member_value","kind"));return new MemberValue(enumeration(Complete.Function.values(),kind,1),kind==1?OptionalValue.of(readDecideValue(u(v,"member_value","decide"))):OptionalValue.absent(),kind==2?optional(u(v,"member_value","choose"),"thinkthen_optional_string_v1",NativeRead::string):OptionalValue.absent(),kind==3?OptionalValue.of(array(u(v,"member_value","tag"),"thinkthen_strings_v1","thinkthen_string_v1",NativeRead::string)):OptionalValue.absent(),kind==4?OptionalValue.of(d(u(v,"member_value","score"))):OptionalValue.absent());}
 static AnnotationMember readAnnotationMember(MemorySegment v){int state=i(f(v,"member","state"));return new AnnotationMember(string(f(v,"member","name")),new Digest(string(f(v,"member","request"))),readQuestion(f(v,"member","question")),enumeration(MemberState.values(),state,1),state==1?OptionalValue.of(readMemberSuccess(u(v,"member","success"))):OptionalValue.absent(),state==2?OptionalValue.of(readMemberFailure(u(v,"member","failure"))):OptionalValue.absent());}
 static RelationAnswer readRelationAnswer(MemorySegment v){String type="relation_answer";int state=i(f(v,type,"state"));return new RelationAnswer(string(f(v,type,"relation")),string(f(v,type,"reads")),enumeration(RelationMethod.values(),i(f(v,type,"method")),1),enumeration(Direction.values(),i(f(v,type,"direction")),1),readEndpoint(f(v,type,"source")),optional(f(v,type,"target"),"thinkthen_optional_endpoint_v1",NativeReaders1::readEndpoint),new Digest(string(f(v,type,"request"))),enumeration(MemberState.values(),state,1),state==1?OptionalValue.of(readRelationSuccess(u(v,type,"success"))):OptionalValue.absent(),state==2?OptionalValue.of(readMemberFailure(u(v,type,"failure"))):OptionalValue.absent());}
 static ObservationIdentity readObservationIdentity(MemorySegment v){int kind=i(f(v,"observation_identity","kind"));return new ObservationIdentity(enumeration(IdentityKind.values(),kind,1),kind==1?OptionalValue.of(new ObservationId(string(u(v,"observation_identity","observation_id")))):OptionalValue.absent(),kind==2?OptionalValue.of(new FailureId(string(u(v,"observation_identity","failure_id")))):OptionalValue.absent());}
 static ObservedProbabilities readObservedProbabilities(MemorySegment v){int kind=i(f(v,"observed_probabilities","kind"));return new ObservedProbabilities(kind==1?OptionalValue.of(d(u(v,"observed_probabilities","yes"))):OptionalValue.absent(),kind==2?OptionalValue.of(probabilities(u(v,"observed_probabilities","named"))):OptionalValue.absent());}
 static ObservationSuccess readObservationSuccess(MemorySegment v){String id=string(f(v,"observation_success","observation_id"));return new ObservationSuccess(new AnswerId(string(f(v,"observation_success","answer_id"))),id.isEmpty()?OptionalValue.absent():OptionalValue.of(new ObservationId(id)),readMemberValue(f(v,"observation_success","value")),readObservedProbabilities(f(v,"observation_success","probabilities")),optional(f(v,"observation_success","confidence"),"thinkthen_optional_double_v1",NativeRead::d));}
static QuestionObservation readQuestionObservation(MemorySegment v){int state=i(f(v,"question_observation","state"));return new QuestionObservation((long)f(v,"question_observation","index").get(JAVA_LONG,0),optional(f(v,"question_observation","member"), "thinkthen_optional_string_v1", x244 -> string(x244)),optional(f(v,"question_observation","stage"), "thinkthen_optional_discriminator_v1", x246 -> enumeration(Stage.values(),x246.get(JAVA_INT,0),1)),(long)f(v,"question_observation","position").get(JAVA_LONG,0),new Digest(string(f(v,"question_observation","question_sha256"))),string(f(v,"question_observation","model")),string(f(v,"question_observation","url")),array(f(v,"question_observation","requests"), "thinkthen_strings_v1", "thinkthen_string_v1", x252 -> new Digest(string(x252))),(long)f(v,"question_observation","requests_sent").get(JAVA_LONG,0),f(v,"question_observation","cached").get(JAVA_INT,0)!=0,(long)f(v,"question_observation","failed_questions").get(JAVA_LONG,0),optional(f(v,"question_observation","usage"), "thinkthen_optional_usage_v1", x257 -> readTokenUsage(x257)),array(f(v,"question_observation","question_sources"), "thinkthen_question_sources_v1", "thinkthen_question_source_v1", x259 -> readQuestionSource(x259)),enumeration(MemberState.values(),f(v,"question_observation","state").get(JAVA_INT,0),1),state==1?OptionalValue.of(readObservationSuccess(u(v,"question_observation","success"))):OptionalValue.absent(),state==2?OptionalValue.of(readMemberFailure(u(v,"question_observation","failure"))):OptionalValue.absent());}
static QuestionMember readQuestionMember(MemorySegment v){MemorySegment p=f(v,"question_member","question").get(ADDRESS,0);return new QuestionMember(string(f(v,"question_member","name")),readQuestion(p.reinterpret(layout("thinkthen_question_view_v1").byteSize())));}
static ObservationEvent readObservationEvent(MemorySegment v){int kind=i(f(v,"observation","kind"));return new ObservationEvent(enumeration(EventKind.values(),kind,1),kind==1?OptionalValue.of(readQuestionObservation(u(v,"observation","question"))):OptionalValue.absent(),kind==2?OptionalValue.of(readRowObservation(u(v,"observation","row"))):OptionalValue.absent());}
static RowObservation readRowObservation(MemorySegment v){int kind=i(f(v,"row_observation","function"));return new RowObservation(l(f(v,"row_observation","index")),new RowValue(enumeration(Complete.Function.values(),kind,1),kind==1?OptionalValue.of(readDecideRow(u(v,"row_observation","decide"))):OptionalValue.absent(),kind==2?OptionalValue.of(readChooseRow(u(v,"row_observation","choose"))):OptionalValue.absent(),kind==3?OptionalValue.of(readTagRow(u(v,"row_observation","tag"))):OptionalValue.absent(),kind==4?OptionalValue.of(readScoreRow(u(v,"row_observation","score"))):OptionalValue.absent(),kind==5?OptionalValue.of(readFilterRow(u(v,"row_observation","filter"))):OptionalValue.absent(),kind==6?OptionalValue.of(readRankRow(u(v,"row_observation","rank"))):OptionalValue.absent(),kind==7?OptionalValue.of(readFindRow(u(v,"row_observation","find"))):OptionalValue.absent(),kind==8?OptionalValue.of(readAnnotateRow(u(v,"row_observation","annotate"))):OptionalValue.absent(),kind==9?OptionalValue.of(readRecognizeRow(u(v,"row_observation","recognize"))):OptionalValue.absent(),kind==10?OptionalValue.of(readRelateRow(u(v,"row_observation","relate"))):OptionalValue.absent()));}
}
