package thinkthen;
import java.lang.foreign.*;
import java.util.*;
import thinkthen.Complete.*;
import thinkthen.Ids.*;
import static thinkthen.NativeLayouts.*;
import static thinkthen.NativeRead.*;
import static java.lang.foreign.ValueLayout.*;
import static thinkthen.NativeReaders1.*;
import static thinkthen.NativeReaders2.*;
final class NativeReaders0 {
 static Rule readRule(MemorySegment v) {return new Rule(enumeration(RuleKind.values(),field(v,"thinkthen_rule_v1","kind").get(JAVA_INT,0),0),field(v,"thinkthen_rule_v1","low").get(JAVA_DOUBLE,0),field(v,"thinkthen_rule_v1","high").get(JAVA_DOUBLE,0));}
 static Choice readChoice(MemorySegment v) {return new Choice(string(field(v,"thinkthen_choice_v1","name")),optional(field(v,"thinkthen_choice_v1","description"), "thinkthen_optional_content_v1", x4 -> readContent(x4)),optional(field(v,"thinkthen_choice_v1","weight"), "thinkthen_optional_double_v1", x6 -> x6.get(JAVA_DOUBLE,0)));}
 static Relation readRelation(MemorySegment v) {return new Relation(string(field(v,"thinkthen_relation_v1","name")),string(field(v,"thinkthen_relation_v1","source")),string(field(v,"thinkthen_relation_v1","target")),optional(field(v,"thinkthen_relation_v1","reads"), "thinkthen_optional_string_v1", x11 -> string(x11)),field(v,"thinkthen_relation_v1","either").get(JAVA_INT,0)!=0,field(v,"thinkthen_relation_v1","single").get(JAVA_INT,0)!=0);}
 static Question readQuestion(MemorySegment v) {return new Question(enumeration(Function.values(),field(v,"thinkthen_question_view_v1","kind").get(JAVA_INT,0),1),readContent(field(v,"thinkthen_question_view_v1","text")),optional(field(v,"thinkthen_question_view_v1","yes"), "thinkthen_optional_content_v1", x19 -> readContent(x19)),optional(field(v,"thinkthen_question_view_v1","no"), "thinkthen_optional_content_v1", x21 -> readContent(x21)),array(field(v,"thinkthen_question_view_v1","choices"), "thinkthen_choices_v1", "thinkthen_choice_v1", x23 -> readChoice(x23)),readRule(field(v,"thinkthen_question_view_v1","threshold")),readRule(field(v,"thinkthen_question_view_v1","relation_threshold")),optional(field(v,"thinkthen_question_view_v1","model"), "thinkthen_optional_string_v1", x27 -> string(x27)),optional(field(v,"thinkthen_question_view_v1","profile"), "thinkthen_optional_string_v1", x29 -> string(x29)),optional(field(v,"thinkthen_question_view_v1","batch"), "thinkthen_optional_size_v1", x31 -> (long)x31.get(JAVA_LONG,0)),field(v,"thinkthen_question_view_v1","batch_max").get(JAVA_INT,0)!=0,field(v,"thinkthen_question_view_v1","none").get(JAVA_INT,0)!=0,array(field(v,"thinkthen_question_view_v1","on"), "thinkthen_strings_v1", "thinkthen_string_v1", x35 -> string(x35)),array(field(v,"thinkthen_question_view_v1","members"), "thinkthen_question_members_v1", "thinkthen_question_member_v1", x37 -> readQuestionMember(x37)),array(field(v,"thinkthen_question_view_v1","kinds"), "thinkthen_choices_v1", "thinkthen_choice_v1", x39 -> readChoice(x39)),array(field(v,"thinkthen_question_view_v1","relations"), "thinkthen_relations_v1", "thinkthen_relation_v1", x41 -> readRelation(x41)),optional(field(v,"thinkthen_question_view_v1","name_pointer"), "thinkthen_optional_string_v1", x43 -> string(x43)),optional(field(v,"thinkthen_question_view_v1","kind_pointer"), "thinkthen_optional_string_v1", x45 -> string(x45)));}
 static Probability readProbability(MemorySegment v) {return new Probability(string(field(v,"thinkthen_probability_v1","name")),field(v,"thinkthen_probability_v1","probability").get(JAVA_DOUBLE,0));}
 static Location readLocation(MemorySegment v) {return new Location(optional(field(v,"thinkthen_location_v1","file"), "thinkthen_optional_string_v1", x49 -> string(x49)),optional(field(v,"thinkthen_location_v1","first_line"), "thinkthen_optional_size_v1", x51 -> (long)x51.get(JAVA_LONG,0)),optional(field(v,"thinkthen_location_v1","last_line"), "thinkthen_optional_size_v1", x53 -> (long)x53.get(JAVA_LONG,0)));}
 static MemberFailure readMemberFailure(MemorySegment v) {return new MemberFailure(new FailureId(string(field(v,"thinkthen_member_failure_v1","failure_id"))),enumeration(MemberCause.values(),field(v,"thinkthen_member_failure_v1","cause").get(JAVA_INT,0),1));}
 static MemberSuccess readMemberSuccess(MemorySegment v) {return new MemberSuccess(new AnswerId(string(field(v,"thinkthen_member_success_v1","answer_id"))),readMemberValue(field(v,"thinkthen_member_success_v1","value")),readAtomicAnswer(field(v,"thinkthen_member_success_v1","answer")),readRule(field(v,"thinkthen_member_success_v1","threshold")));}
 static Entity readEntity(MemorySegment v) {return new Entity(string(field(v,"thinkthen_entity_v1","text")),(long)field(v,"thinkthen_entity_v1","start").get(JAVA_LONG,0),(long)field(v,"thinkthen_entity_v1","end").get(JAVA_LONG,0),(long)field(v,"thinkthen_entity_v1","length").get(JAVA_LONG,0),string(field(v,"thinkthen_entity_v1","kind")),field(v,"thinkthen_entity_v1","strength").get(JAVA_DOUBLE,0));}
 static EntityEdge readEntityEdge(MemorySegment v) {return new EntityEdge(string(field(v,"thinkthen_entity_edge_v1","relation")),readEntity(field(v,"thinkthen_entity_edge_v1","source")),readEntity(field(v,"thinkthen_entity_edge_v1","target")),field(v,"thinkthen_entity_edge_v1","probability").get(JAVA_DOUBLE,0),field(v,"thinkthen_entity_edge_v1","either").get(JAVA_INT,0)!=0);}
 static Place readPlace(MemorySegment v) {return new Place((long)field(v,"thinkthen_place_v1","start").get(JAVA_LONG,0),(long)field(v,"thinkthen_place_v1","end").get(JAVA_LONG,0));}
 static Piece readPiece(MemorySegment v) {return new Piece((long)field(v,"thinkthen_piece_v1","start").get(JAVA_LONG,0),(long)field(v,"thinkthen_piece_v1","end").get(JAVA_LONG,0),array(field(v,"thinkthen_piece_v1","tags"), "thinkthen_probabilities_v1", "thinkthen_probability_v1", x76 -> readProbability(x76)));}
 static NameSpan readNameSpan(MemorySegment v) {return new NameSpan((long)field(v,"thinkthen_name_v1","start").get(JAVA_LONG,0),(long)field(v,"thinkthen_name_v1","end").get(JAVA_LONG,0),optional(field(v,"thinkthen_name_v1","kinds"), "thinkthen_optional_probabilities_v1", x80 -> array(x80, "thinkthen_probabilities_v1", "thinkthen_probability_v1", x81 -> readProbability(x81))),optional(field(v,"thinkthen_name_v1","edges"), "thinkthen_optional_probabilities_v1", x83 -> array(x83, "thinkthen_probabilities_v1", "thinkthen_probability_v1", x84 -> readProbability(x84))));}
 static PairSpan readPairSpan(MemorySegment v) {return new PairSpan(string(field(v,"thinkthen_pair_v1","relation")),readPlace(field(v,"thinkthen_pair_v1","source")),readPlace(field(v,"thinkthen_pair_v1","target")),field(v,"thinkthen_pair_v1","probability").get(JAVA_DOUBLE,0));}
}
