package thinkthen;
import java.lang.foreign.*;
import java.util.*;
import thinkthen.Complete.*;
import thinkthen.Ids.*;
import static thinkthen.NativeLayouts.*;
import static thinkthen.NativeRead.*;
import static java.lang.foreign.ValueLayout.*;
import static thinkthen.NativeReaders0.*;
import static thinkthen.NativeReaders2.*;
final class NativeReaders1 {
 static RecognizeValue readRecognizeValue(MemorySegment v) {return new RecognizeValue(array(field(v,"thinkthen_recognize_value_v1","entities"), "thinkthen_entities_v1", "thinkthen_entity_v1", x90 -> readEntity(x90)),optional(field(v,"thinkthen_recognize_value_v1","relations"), "thinkthen_optional_entity_edges_v1", x92 -> array(x92, "thinkthen_entity_edges_v1", "thinkthen_entity_edge_v1", x93 -> readEntityEdge(x93))));}
 static RecognizeAnswer readRecognizeAnswer(MemorySegment v) {return new RecognizeAnswer(array(field(v,"thinkthen_recognize_answer_v1","pieces"), "thinkthen_pieces_v1", "thinkthen_piece_v1", x95 -> readPiece(x95)),array(field(v,"thinkthen_recognize_answer_v1","names"), "thinkthen_names_v1", "thinkthen_name_v1", x97 -> readNameSpan(x97)),array(field(v,"thinkthen_recognize_answer_v1","pairs"), "thinkthen_pairs_v1", "thinkthen_pair_v1", x99 -> readPairSpan(x99)));}
 static Endpoint readEndpoint(MemorySegment v) {return new Endpoint(string(field(v,"thinkthen_endpoint_v1","name")),string(field(v,"thinkthen_endpoint_v1","kind")));}
 static Edge readEdge(MemorySegment v) {return new Edge(string(field(v,"thinkthen_edge_v1","relation")),readEndpoint(field(v,"thinkthen_edge_v1","source")),readEndpoint(field(v,"thinkthen_edge_v1","target")),field(v,"thinkthen_edge_v1","probability").get(JAVA_DOUBLE,0),field(v,"thinkthen_edge_v1","either").get(JAVA_INT,0)!=0);}
 static RelationSuccess readRelationSuccess(MemorySegment v) {return new RelationSuccess(new AnswerId(string(field(v,"thinkthen_relation_success_v1","answer_id"))),field(v,"thinkthen_relation_success_v1","probability").get(JAVA_DOUBLE,0),field(v,"thinkthen_relation_success_v1","accepted").get(JAVA_INT,0)!=0);}
 static TokenUsage readTokenUsage(MemorySegment v) {return new TokenUsage((long)field(v,"thinkthen_usage_v1","input_tokens").get(JAVA_LONG,0),(long)field(v,"thinkthen_usage_v1","output_tokens").get(JAVA_LONG,0));}
 static QuestionSource readQuestionSource(MemorySegment v) {return new QuestionSource(enumeration(Origin.values(),field(v,"thinkthen_question_source_v1","origin").get(JAVA_INT,0),1),string(field(v,"thinkthen_question_source_v1","answered_by")));}
 static ProfileWarning readProfileWarning(MemorySegment v) {return new ProfileWarning(string(field(v,"thinkthen_profile_warning_v1","tuned_for")),string(field(v,"thinkthen_profile_warning_v1","running")));}
 static BatchSetting readBatchSetting(MemorySegment v) {return new BatchSetting(enumeration(BatchKind.values(),field(v,"thinkthen_batch_v1","kind").get(JAVA_INT,0),1),(long)field(v,"thinkthen_batch_v1","records").get(JAVA_LONG,0));}
 static BatchWarning readBatchWarning(MemorySegment v) {return new BatchWarning(readBatchSetting(field(v,"thinkthen_batch_warning_v1","tuned_for")),readBatchSetting(field(v,"thinkthen_batch_warning_v1","running")));}
 static Attempt readAttempt(MemorySegment v) {return new Attempt((long)field(v,"thinkthen_attempt_v1","ordinal").get(JAVA_LONG,0),new Digest(string(field(v,"thinkthen_attempt_v1","request_sha256"))),(long)field(v,"thinkthen_attempt_v1","wall_ms").get(JAVA_LONG,0),enumeration(AttemptOutcome.values(),field(v,"thinkthen_attempt_v1","outcome").get(JAVA_INT,0),1),new SdkRequestId(string(field(v,"thinkthen_attempt_v1","sdk_request_id"))),optional(field(v,"thinkthen_attempt_v1","status"), "thinkthen_optional_u16_v1", x126 -> (long)x126.get(JAVA_SHORT,0)),optional(field(v,"thinkthen_attempt_v1","server_ms"), "thinkthen_optional_u64_v1", x128 -> (long)x128.get(JAVA_LONG,0)),optional(field(v,"thinkthen_attempt_v1","request_id"), "thinkthen_optional_string_v1", x130 -> string(x130)));}
 static Meta readMeta(MemorySegment v) {return new Meta(string(field(v,"thinkthen_meta_v1","tool")),optional(field(v,"thinkthen_meta_v1","question_sha256"), "thinkthen_optional_string_v1", x133 -> new Digest(string(x133))),optional(field(v,"thinkthen_meta_v1","questions_sha256"), "thinkthen_optional_string_v1", x135 -> new Digest(string(x135))),string(field(v,"thinkthen_meta_v1","url")),string(field(v,"thinkthen_meta_v1","model")),optional(field(v,"thinkthen_meta_v1","usage"), "thinkthen_optional_usage_v1", x139 -> readTokenUsage(x139)),(long)field(v,"thinkthen_meta_v1","requests_sent").get(JAVA_LONG,0),field(v,"thinkthen_meta_v1","cached").get(JAVA_INT,0)!=0,array(field(v,"thinkthen_meta_v1","requests"), "thinkthen_strings_v1", "thinkthen_string_v1", x143 -> new Digest(string(x143))),(long)field(v,"thinkthen_meta_v1","failed_questions").get(JAVA_LONG,0),optional(field(v,"thinkthen_meta_v1","profile_warning"), "thinkthen_optional_profile_warning_v1", x146 -> readProfileWarning(x146)),optional(field(v,"thinkthen_meta_v1","batch_setting"), "thinkthen_optional_batch_v1", x148 -> readBatchSetting(x148)),optional(field(v,"thinkthen_meta_v1","batch_warning"), "thinkthen_optional_batch_warning_v1", x150 -> readBatchWarning(x150)),optional(field(v,"thinkthen_meta_v1","context_sha256"), "thinkthen_optional_string_v1", x152 -> new Digest(string(x152))),optional(field(v,"thinkthen_meta_v1","attempts"), "thinkthen_optional_attempts_v1", x154 -> array(x154, "thinkthen_attempts_v1", "thinkthen_attempt_v1", x155 -> readAttempt(x155))),optional(field(v,"thinkthen_meta_v1","origin"), "thinkthen_optional_discriminator_v1", x157 -> enumeration(Origin.values(),x157.get(JAVA_INT,0),1)),array(field(v,"thinkthen_meta_v1","question_sources"), "thinkthen_question_sources_v1", "thinkthen_question_source_v1", x159 -> readQuestionSource(x159)),array(field(v,"thinkthen_meta_v1","observations"), "thinkthen_observation_identities_v1", "thinkthen_observation_identity_v1", x161 -> readObservationIdentity(x161)),optional(field(v,"thinkthen_meta_v1","answered_by"), "thinkthen_optional_string_v1", x163 -> string(x163)));}
 static CallFacts readCallFacts(MemorySegment v) {return new CallFacts(new CallId(string(field(v,"thinkthen_facts_v1","call_id"))),(long)field(v,"thinkthen_facts_v1","cache_answers").get(JAVA_LONG,0),optional(field(v,"thinkthen_facts_v1","estimated_cost_usd"), "thinkthen_optional_string_v1", x167 -> string(x167)),optional(field(v,"thinkthen_facts_v1","input_tokens"), "thinkthen_optional_u64_v1", x169 -> (long)x169.get(JAVA_LONG,0)),optional(field(v,"thinkthen_facts_v1","model"), "thinkthen_optional_string_v1", x171 -> string(x171)),optional(field(v,"thinkthen_facts_v1","output_tokens"), "thinkthen_optional_u64_v1", x173 -> (long)x173.get(JAVA_LONG,0)),(long)field(v,"thinkthen_facts_v1","records").get(JAVA_LONG,0),(long)field(v,"thinkthen_facts_v1","requests_sent").get(JAVA_LONG,0),field(v,"thinkthen_facts_v1","seconds").get(JAVA_DOUBLE,0),optional(field(v,"thinkthen_facts_v1","command_ms"), "thinkthen_optional_u64_v1", x178 -> (long)x178.get(JAVA_LONG,0)));}
 static Stopped readStopped(MemorySegment v) {return new Stopped(optional(field(v,"thinkthen_stopped_v1","at"), "thinkthen_optional_size_v1", x180 -> (long)x180.get(JAVA_LONG,0)),enumeration(StopCause.values(),field(v,"thinkthen_stopped_v1","cause").get(JAVA_INT,0),1),optional(field(v,"thinkthen_stopped_v1","status"), "thinkthen_optional_u16_v1", x183 -> (long)x183.get(JAVA_SHORT,0)),field(v,"thinkthen_stopped_v1","retryable").get(JAVA_INT,0)!=0);}
 static CommonRow readCommonRow(MemorySegment v) {return new CommonRow(new AnswerId(string(field(v,"thinkthen_row_v1","answer_id"))),optional(field(v,"thinkthen_row_v1","input"), "thinkthen_optional_content_v1", x187 -> readContent(x187)),optional(field(v,"thinkthen_row_v1","question"), "thinkthen_optional_question_v1", x189 -> readQuestion(x189)),optional(field(v,"thinkthen_row_v1","answer"), "thinkthen_optional_answer_v1", x191 -> readAtomicAnswer(x191)),optional(field(v,"thinkthen_row_v1","threshold"), "thinkthen_optional_rule_v1", x193 -> readRule(x193)),optional(field(v,"thinkthen_row_v1","position"), "thinkthen_optional_location_v1", x195 -> readLocation(x195)),optional(field(v,"thinkthen_row_v1","input_file"), "thinkthen_optional_string_v1", x197 -> string(x197)),readMeta(field(v,"thinkthen_row_v1","meta")),optional(field(v,"thinkthen_row_v1","images"), "thinkthen_optional_image_views_v1", x200 -> array(x200, "thinkthen_image_views_v1", "thinkthen_image_view_v1", x201 -> readImageView(x201))));}
}
