      *> Closed discriminators from the reviewed unpublished C contract.
       78 tt-c-content-text-v1 value 1.
       78 tt-c-content-json-v1 value 2.
       78 tt-c-rule-default-v1 value 0.
       78 tt-c-rule-null-v1 value 1.
       78 tt-c-rule-cut-v1 value 2.
       78 tt-c-rule-band-v1 value 3.
       78 tt-c-function-decide-v1 value 1.
       78 tt-c-function-choose-v1 value 2.
       78 tt-c-function-tag-v1 value 3.
       78 tt-c-function-score-v1 value 4.
       78 tt-c-function-filter-v1 value 5.
       78 tt-c-function-rank-v1 value 6.
       78 tt-c-function-find-v1 value 7.
       78 tt-c-function-annotate-v1 value 8.
       78 tt-c-function-recognize-v1 value 9.
       78 tt-c-function-relate-v1 value 10.
       78 tt-c-image-jpeg-v1 value 1.
       78 tt-c-image-png-v1 value 2.
       78 tt-c-source-line-v1 value 1.
       78 tt-c-source-window-v1 value 2.
       78 tt-c-source-file-v1 value 3.
       78 tt-c-source-image-file-v1 value 4.
       78 tt-c-decide-null-v1 value 0.
       78 tt-c-decide-boolean-v1 value 1.
       78 tt-c-decide-authored-v1 value 2.
       78 tt-c-answer-yes-no-v1 value 1.
       78 tt-c-answer-choice-v1 value 2.
       78 tt-c-answer-tag-v1 value 3.
       78 tt-c-answer-score-v1 value 4.
       78 tt-c-answer-find-v1 value 5.
       78 tt-c-member-success-v1 value 1.
       78 tt-c-member-failure-v1 value 2.
       78 tt-c-member-missing-answer-v1 value 1.
       78 tt-c-member-wrong-kind-v1 value 2.
       78 tt-c-member-missing-probability-v1 value 3.
       78 tt-c-member-invalid-probability-v1 value 4.
       78 tt-c-member-invalid-distribution-v1 value 5.
       78 tt-c-member-unexpected-probability-v1 value 6.
       78 tt-c-relation-yes-no-v1 value 1.
       78 tt-c-relation-choice-v1 value 2.
       78 tt-c-direction-source-to-target-v1 value 1.
       78 tt-c-direction-either-v1 value 2.
       78 tt-c-origin-live-v1 value 1.
       78 tt-c-origin-cache-v1 value 2.
       78 tt-c-origin-replay-v1 value 3.
       78 tt-c-origin-proxy-v1 value 4.
       78 tt-c-origin-memory-v1 value 5.
       78 tt-c-id-observation-v1 value 1.
       78 tt-c-id-failure-v1 value 2.
       78 tt-c-batch-records-v1 value 1.
       78 tt-c-batch-max-v1 value 2.
       78 tt-c-attempt-ok-v1 value 1.
       78 tt-c-attempt-status-v1 value 2.
       78 tt-c-attempt-transport-v1 value 3.
       78 tt-c-stop-usage-v1 value 1.
       78 tt-c-stop-local-v1 value 2.
       78 tt-c-stop-no-key-v1 value 3.
       78 tt-c-stop-transport-v1 value 4.
       78 tt-c-stop-status-v1 value 5.
       78 tt-c-stop-too-large-v1 value 6.
       78 tt-c-stop-reply-v1 value 7.
       78 tt-c-stop-backend-v1 value 8.
       78 tt-c-stop-cancelled-v1 value 9.
       78 tt-c-stop-defect-v1 value 10.
       78 tt-c-stop-deadline-v1 value 11.
       78 tt-c-stage-boundary-v1 value 1.
       78 tt-c-stage-kind-v1 value 2.
       78 tt-c-stage-edge-v1 value 3.
       78 tt-c-stage-relation-v1 value 4.
       78 tt-c-probabilities-yes-v1 value 1.
       78 tt-c-probabilities-named-v1 value 2.
       78 tt-c-event-question-v1 value 1.
       78 tt-c-event-row-v1 value 2.
       78 tt-c-result-success-v1 value 1.
       78 tt-c-result-failure-v1 value 2.
