using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using ThinkThen;

// JSON frames shared fixtures; all known outputs come from typed native getters.
static class NativeCases {
 static object? Opt<T>(Optional<T> v)=>v.Present?v.Value:null;
 static JsonElement Get(JsonElement d,string key)=>d.ValueKind==JsonValueKind.Object&&d.TryGetProperty(key,out var v)?v:default;
 static bool Yes(JsonElement d,string key)=>Get(d,key).ValueKind==JsonValueKind.True;
 static string Text(JsonElement d,string key)=>Get(d,key).ValueKind==JsonValueKind.String?Get(d,key).GetString()!:"";
 static Content Content(JsonElement v,bool text)=>text&&v.ValueKind==JsonValueKind.String?new(ContentKind.Text,v.GetString()!,default):new(ContentKind.Json,"",v.Clone());
 static object? Original(Content c)=>c.Kind==ContentKind.Text?c.Text:c.Json;
 static QuestionInput Question(JsonElement d){string verb=Text(d,"verb");var q=Get(d,"question");var role=verb switch{"annotate"=>QuestionRole.Set,"rank"=>Get(q,"questions").ValueKind!=JsonValueKind.Undefined?QuestionRole.RankSet:QuestionRole.Rank,"find"=>QuestionRole.Find,"recognize"=>QuestionRole.Recognize,"relate"=>QuestionRole.Relate,"choose"=>Get(q,"options").ValueKind==JsonValueKind.Undefined?QuestionRole.DynamicChoose:QuestionRole.Atomic,_=>QuestionRole.Atomic};
  switch(Text(d,"loader")){case "load_named":case "named":return QuestionInput.NamedQuestion(role,Text(d,"reference"));case "load_reference":case "reference":return QuestionInput.QuestionReference(role,Text(d,"reference"));case "load":case "file":return QuestionInput.QuestionFile(Text(d,"reference"));}
  if(Text(d,"question_form")=="file")return QuestionInput.QuestionFile("fixture-question.json");
  if(verb=="find"&&Yes(q,"none")){var spec=Questions.Find(Content(Get(q,"find"),true)) with {None=true};var metadata=Get(d,"metadata");if(metadata.ValueKind==JsonValueKind.Object)spec=spec with {Author=Optional.Some(new QuestionAuthor(Optional.Some(Text(metadata,"name")),Optional.Some(Get(metadata,"wording_version").GetUInt64()),new InputDeclaration(DeclarationKind.Absent,Array.Empty<InputProperty>(),Array.Empty<string>()),new InputDeclaration(DeclarationKind.Absent,Array.Empty<InputProperty>(),Array.Empty<string>())))};return QuestionInput.Asked(spec);}
  return QuestionInput.SavedQuestion(role,Get(d,"raw").ValueKind==JsonValueKind.String?Text(d,"raw"):q.GetRawText());
 }
 static InputSource Source(JsonElement d){var paths=Get(d,"paths");if(paths.ValueKind==JsonValueKind.Array&&paths.GetArrayLength()>0)return InputSource.FromFiles(new FileSource(paths.EnumerateArray().Select(v=>v.GetString()!).ToArray(),(SourceUnit)(Get(d,"source_unit").GetInt32()-1),Get(d,"window").ValueKind==JsonValueKind.Number?Get(d,"window").GetUInt64():0){ImageReader=Yes(d,"image_reader")});
  var images=new List<ImageInput>();var imagePaths=Get(d,"image_paths");if(imagePaths.ValueKind==JsonValueKind.Array)foreach(var p in imagePaths.EnumerateArray())images.Add(new(Text(d,"media")=="image/jpeg"?Media.Jpeg:Media.Png,File.ReadAllBytes(p.GetString()!),default));
  var records=new List<RecordInput>();int at=0;foreach(var item in Get(d,"items").EnumerateArray()){var caption=Yes(d,"caption_files")?new Content(ContentKind.Text,File.ReadAllText($"caption-{at}.txt"),default):Content(item,Yes(d,"text"));var orders=Get(d,"candidate_orders");var options=orders.ValueKind==JsonValueKind.Array?orders[at].EnumerateArray().Select(n=>new Choice(n.GetString()!,default,default)).ToArray():Array.Empty<Choice>();at++;records.Add(new(Yes(d,"image_only")?default:Optional.Some(caption),Yes(d,"context_present")?Optional.Some(Content(Get(d,"context"),true)):default,options,images));}return InputSource.FromRecords(records);
 }
 public static string Run(string raw){using var document=JsonDocument.Parse(raw);var d=document.RootElement;Thread? cancellationThread=null;try{using var e=Engine.Open(Text(d,"engine_settings"));var q=Question(d);var s=Source(d);var context=Get(d,"shared_context");var c=new CallControls(context.ValueKind is JsonValueKind.Undefined or JsonValueKind.Null?default:Optional.Some(Content(context,true)),default,false,true);using var cancel=new CancellationTokenSource();string injection=Text(Get(d,"operation"),"injection");if(injection=="cancel_token")cancel.Cancel();if(Yes(d,"held_cancel")){cancellationThread=new Thread(()=>{if(Console.Read()!='!')throw new Exception("missing cancellation signal");cancel.Cancel();Console.WriteLine("cancel-fired");Console.Out.Flush();});cancellationThread.Start();}TimeSpan? budget=injection=="expired_deadline"?TimeSpan.Zero:null;object result;
  if(Yes(d,"incremental"))result=Text(d,"verb") switch{
   "decide"=>Batch(e.DecideBatch(q,s,c,budget,cancel.Token)),"choose"=>Batch(e.ChooseBatch(q,s,c,budget,cancel.Token)),"tag"=>Batch(e.TagBatch(q,s,c,budget,cancel.Token)),"score"=>Batch(e.ScoreBatch(q,s,c,budget,cancel.Token)),"filter"=>Batch(e.FilterBatch(q,s,c,budget,cancel.Token)),"annotate"=>Batch(e.AnnotateBatch(q,s,c,budget,cancel.Token)),_=>throw new InvalidOperationException("function has no native batch")};
  else result=Text(d,"verb") switch{
   "decide"=>Normalize(e.DecideComplete(q,s,c,budget,cancel.Token)),"choose"=>Normalize(e.ChooseComplete(q,s,c,budget,cancel.Token)),"tag"=>Normalize(e.TagComplete(q,s,c,budget,cancel.Token)),"score"=>Normalize(e.ScoreComplete(q,s,c,budget,cancel.Token)),"filter"=>Normalize(e.FilterComplete(q,s,c,budget,cancel.Token)),"rank"=>Normalize(e.RankComplete(q,s,c,budget,cancel.Token)),"find"=>Normalize(e.FindComplete(q,s,c,budget,cancel.Token)),"annotate"=>Normalize(e.AnnotateComplete(q,s,c,budget,cancel.Token)),"recognize"=>Normalize(e.RecognizeComplete(q,s,c,budget,cancel.Token)),"relate"=>Normalize(e.RelateComplete(q,s,c,budget,cancel.Token)),_=>throw new InvalidOperationException("unknown function")};if(cancellationThread!=null)cancellationThread.Join();return JsonSerializer.Serialize(result);
 }catch(Failure f){return JsonSerializer.Serialize(Error((ulong)f.Code,f.Message,f.Complete));}finally{cancellationThread?.Join();}}
 static Dictionary<string,object?> Batch<T>(CompleteBatch<T> batch){var rows=new List<object?>();using(batch){try{while(true){var part=batch.Next();if(part==null)break;var outp=Normalize(part);if(!Equals(outp["code"],0)){outp["completed"]=rows;return outp;}rows.AddRange(part.Rows.Select(r=>(object?)Row(r!,part.Observations)));}var output=Normalize(batch.Facts()??throw new Exception("batch has no facts"));output["completed"]=rows;output["rows"]=rows;return output;}catch(Failure f){var output=Error((ulong)f.Code,f.Message,f.Complete);output["completed"]=rows;return output;}}}
 static Dictionary<string,object?> Error(ulong code,string message,Optional<CompleteError> detail){var o=new Dictionary<string,object?>{{"code",code},{"message",message}};if(detail.Present){var e=detail.Value;if(e.Facts.Present){o["requests_sent"]=e.Facts.Value.RequestsSent;o["records"]=e.Facts.Value.Records;}if(e.Stopped.Present)o["stopped_at"]=Opt(e.Stopped.Value.At);}return o;}
 static Dictionary<string,object?> Normalize<T>(CompleteCall<T> c){if(c.Error.Present)return Error(c.Error.Value.Code,c.Error.Value.Message,c.Error);var o=new Dictionary<string,object?>{{"code",0},{"schema",c.Schema},{"observations",c.Observations.Count},{"rows",c.Rows.Select(r=>Row(r!,c.Observations)).ToArray()}};if(c.Facts.Present){o["call_id"]=c.Facts.Value.CallId.Value;o["requests_sent"]=c.Facts.Value.RequestsSent;o["cache_answers"]=c.Facts.Value.CacheAnswers;}return o;}
 static object? Decide(DecideValue v)=>v.Kind switch{ValueKind.Boolean=>v.Boolean,ValueKind.Authored=>Original(v.Authored.Value),_=>null};
 static object? Member(MemberValue v)=>v.Function switch{Function.Decide=>Decide(v.Decide.Value),Function.Choose=>Opt(v.Choose),Function.Tag=>Opt(v.Tag),Function.Score=>Opt(v.Score),_=>throw new InvalidOperationException("non-atomic member")};
 static object Entity(Entity e)=>new {text=e.Text,start=e.Start,end=e.End,length=e.Length,kind=e.Kind,strength=e.Strength};
 static object Endpoint(Endpoint e)=>new {name=e.Name,kind=e.Kind};
 static object Edge(string relation,object source,object target,double probability,bool either){var o=new Dictionary<string,object?>{{"relation",relation},{"source",source},{"target",target},{"probability",probability}};if(either)o["either"]=true;return o;}
 static object Edges(IReadOnlyList<Edge> v)=>v.Select(e=>Edge(e.Relation,Endpoint(e.Source),Endpoint(e.Target),e.Probability,e.Either)).ToArray();
 static object Recognized(RecognizeValue v){var o=new Dictionary<string,object?>{{"entities",v.Entities.Select(Entity).ToArray()}};if(v.Relations.Present)o["relations"]=v.Relations.Value.Select(e=>Edge(e.Relation,Entity(e.Source),Entity(e.Target),e.Probability,e.Either)).ToArray();return o;}
 static CommonRow Common(object r)=>r switch{DecideRow x=>x.Common,ChooseRow x=>x.Common,TagRow x=>x.Common,ScoreRow x=>x.Common,FilterRow x=>x.Common,RankRow x=>x.Common,FindRow x=>x.Common,AnnotateRow x=>x.Common,RecognizeRow x=>x.Common,RelateRow x=>x.Common,_=>throw new InvalidOperationException("unknown row")};
 static object Observed(RowValue r)=>r.Function switch{Function.Decide=>r.Decide.Value,Function.Choose=>r.Choose.Value,Function.Tag=>r.Tag.Value,Function.Score=>r.Score.Value,Function.Filter=>r.Filter.Value,Function.Rank=>r.Rank.Value,Function.Find=>r.Find.Value,Function.Annotate=>r.Annotate.Value,Function.Recognize=>r.Recognize.Value,Function.Relate=>r.Relate.Value,_=>throw new InvalidOperationException("unknown observation")};
 static void Location(Dictionary<string,object?> o,Optional<Location> p){if(!p.Present)return;var l=p.Value;if(l.File.Present)o["file"]=l.File.Value;if(l.FirstLine.Present)o["first_line"]=l.FirstLine.Value;if(l.LastLine.Present)o["last_line"]=l.LastLine.Value;}
 static Dictionary<string,object?> Author(QuestionAuthor? a){var o=new Dictionary<string,object?>();if(a!=null){if(a.Name.Present)o["name"]=a.Name.Value;if(a.WordingVersion.Present)o["wording_version"]=a.WordingVersion.Value;}return o;}
 static string Cause(MemberCause c)=>c switch{MemberCause.MissingAnswer=>"missing_answer",MemberCause.WrongKind=>"wrong_kind",MemberCause.MissingProbability=>"missing_probability",MemberCause.InvalidProbability=>"invalid_probability",MemberCause.InvalidDistribution=>"invalid_distribution",_=>"unexpected_probability"};
 static Dictionary<string,object?> Row(object r,IReadOnlyList<ObservationEvent> events){var c=Common(r);object? value=r switch{DecideRow x=>Decide(x.Value),ChooseRow x=>Opt(x.Value),TagRow x=>x.Value,ScoreRow x=>x.Value,FilterRow x=>x.Value,RankRow x=>Opt(x.Value),FindRow x=>x.Value.Present?Original(x.Value.Value):null,AnnotateRow x=>x.Answers.ToDictionary(m=>m.Name,m=>m.Success.Present?Member(m.Success.Value.Value):new {failed=new {kind="backend",cause=Cause(m.Failure.Value.Cause)}}),RecognizeRow x=>Recognized(x.Value),RelateRow x=>Edges(x.Value),_=>throw new InvalidOperationException("unknown row")};ulong index=0;foreach(var e in events)if(e.Row.Present&&Common(Observed(e.Row.Value.Value)).AnswerId==c.AnswerId){index=e.Row.Value.Index;break;}
  var o=new Dictionary<string,object?>{{"value",value},{"index",r is FindRow find?Opt(find.Index):index},{"answer_id",c.AnswerId.Value},{"origin",c.Meta.Origin.Present?(int)c.Meta.Origin.Value+1:null},{"answered_by",Opt(c.Meta.AnsweredBy)},{"observations",c.Meta.Observations.Count},{"sources",c.Meta.QuestionSources.Count},{"input",c.Input.Present?Original(c.Input.Value):null}};Location(o,c.Position);foreach(var a in Author(c.Author))o[a.Key]=a.Value;o["observation_ids"]=c.Meta.Observations.Where(i=>i.ObservationId.Present).Select(i=>i.ObservationId.Value.Value).ToArray();if(c.Images.Present)o["image_properties"]=c.Images.Value.Select(i=>new ulong[]{(ulong)i.Media+1,i.Width,i.Height}).ToArray();if(c.Images.Present)o["images"]=c.Images.Value.Select(i=>Convert.ToHexString(i.Bytes).ToLowerInvariant()).ToArray();if(c.Answer.Present){var a=c.Answer.Value;o["answer_kind"]=a.Kind==AtomicKind.Find?"find":a.Kind.ToString();if(a.Probability.Present)o["probability"]=a.Probability.Value;else o["probabilities"]=a.Probabilities.ToDictionary(p=>p.Name,p=>p.Value);}o["detail_inputs"]=c.Details!.Inputs.Select(i=>{var input=new Dictionary<string,object?>{{"input",i.Original.Present?Original(i.Original.Value):null}};Location(input,i.Position);return input;}).ToArray();if(r is AnnotateRow annotate)o["member_authors"]=annotate.Answers.Select(m=>Author(m.Author)).ToArray();return o;
 }
}
