<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup><ItemGroup><Compile Include="source/Program.cs"/><Compile Include="../src/*.cs" /><Compile Include="../../../sdlc/generators/results/csharp/CompleteFacts.g.cs"/><None Include="../../c/target/debug/libthinkthen_c.so" Link="libthinkthen.so" CopyToOutputDirectory="PreserveNewest" Condition="Exists('../../c/target/debug/libthinkthen_c.so')"/></ItemGroup></Project>
