if(NOT DEFINED THINKTHEN_EXTENSION_VERSION)
  message(FATAL_ERROR "Set THINKTHEN_EXTENSION_VERSION from the ThinkThen package")
endif()
duckdb_extension_load(thinkthen
  SOURCE_DIR ${CMAKE_CURRENT_LIST_DIR}
  DONT_LINK
  EXTENSION_VERSION ${THINKTHEN_EXTENSION_VERSION})
