'use strict';
// The JavaScript entry over the native door. The loader (loader.cjs) is
// generated by napi-rs. This file shapes arguments into the contract's
// grammar and the contract's answers into JavaScript values, and raises the
// engine's failures as ThinkThenError. Nothing else lives here: no rule,
// no retry, no sending, and no threshold math beyond spelling a band as
// the file grammar does.

const native = require('./loader.cjs');

const QUESTION_KINDS = ['decide', 'choose', 'score', 'tag'];

/** The host's own error class. `kind` is one of the six kinds and
 * `retryable` carries the engine's verdict on a second try. A failure is
 * never a value: no call resolves `false` because it failed. */
class ThinkThenError extends Error {
  constructor(kind, message, retryable) {
    super(message);
    this.name = 'ThinkThenError';
    this.kind = kind;
    this.retryable = retryable;
  }
}

function usageError(message) {
  return new ThinkThenError('usage', message, false);
}

function isQuestion(value) {
  return typeof value === 'function' && value.__question === true;
}

// The file grammar's JSON for a question. A band given as [low, high]
// becomes the file's "low:high" string; everything else passes through and
// the engine rules on it.
function specOf(question) {
  let spec;
  if (isQuestion(question)) spec = JSON.parse(question.__spec);
  else if (typeof question === 'string') spec = { decide: question };
  else if (question && typeof question === 'object' && !Array.isArray(question)) {
    spec = { ...question };
  } else {
    throw usageError('the question is missing: text, file keys, or a question value');
  }
  if (!QUESTION_KINDS.some((kind) => Object.prototype.hasOwnProperty.call(spec, kind))) {
    throw usageError('the question names no decide, choose, score, or tag');
  }
  if (Array.isArray(spec.threshold)) {
    const [low, high] = spec.threshold;
    if (typeof low !== 'number' || typeof high !== 'number') {
      throw usageError('a band threshold is [low, high], two numbers');
    }
    spec.threshold = `${low}:${high}`;
  }
  return spec;
}

// Build a question value. A function, so no spread or stringify turns it
// back into text by accident; `__spec` holds the file grammar's JSON.
function question(spec) {
  if (!spec || typeof spec !== 'object' || Array.isArray(spec)) {
    throw usageError('question takes an object: { decide | choose | score | tag, ... }');
  }
  const held = () => {
    throw usageError('a question value is asked, not called');
  };
  held.__question = true;
  held.__spec = JSON.stringify(specOf(spec));
  return held;
}

function callOptions(options) {
  const out = {};
  if (options === undefined || options === null) return out;
  if (typeof options !== 'object' || Array.isArray(options)) {
    throw usageError('options is an object: { signal, deadlineMs }');
  }
  const { signal, deadlineMs } = options;
  if (signal !== undefined) {
    if (!signal || typeof signal.aborted !== 'boolean' || typeof signal.addEventListener !== 'function') {
      throw usageError('options.signal must be an AbortSignal');
    }
    const handle = new native.CancelHandle();
    const stop = () => handle.cancel();
    if (signal.aborted) stop();
    else signal.addEventListener('abort', stop, { once: true });
    out.cancel = handle;
  }
  if (deadlineMs !== undefined) {
    const held = Number(deadlineMs);
    if (!Number.isFinite(held) || held <= 0) {
      throw usageError('options.deadlineMs is positive milliseconds');
    }
    out.deadlineSec = held / 1000;
  }
  return out;
}

async function invoke(op, spec, payload, options) {
  const { cancel, deadlineSec } = callOptions(options);
  const envelope = await native.call(op, spec ?? null, payload, cancel ?? null, deadlineSec ?? null);
  const parsed = JSON.parse(envelope);
  if (parsed.err) {
    throw new ThinkThenError(parsed.err.kind, parsed.err.message, parsed.err.retryable);
  }
  return parsed.ok;
}

function bare(answer) {
  if (answer === 'yes') return true;
  if (answer === 'no') return false;
  if (answer === 'unsure') return null;
  throw new ThinkThenError('defect', `the door carried an unknown answer ${answer}`, false);
}

function checkEvidence(text) {
  if (typeof text !== 'string') throw usageError('the evidence is text');
}

function checkRecords(records) {
  if (!Array.isArray(records)) throw usageError('records is an array of strings');
  for (const held of records) {
    if (typeof held !== 'string') throw usageError('records is an array of strings');
  }
  return records;
}

async function decide(questionOrText, text, options) {
  checkEvidence(text);
  const spec = JSON.stringify(specOf(questionOrText));
  return bare(await invoke('decide', spec, text, options));
}

// decide's bulk spelling: the same answer, once per record, in order.
async function decide_many(question, records, options) {
  const spec = JSON.stringify(specOf(question));
  const judgments = await invoke('decide_many', spec, JSON.stringify(checkRecords(records)), options);
  return judgments.map((held) => bare(held.answer));
}

async function choose(questionOrSpec, text, options) {
  checkEvidence(text);
  const spec = JSON.stringify(specOf(questionOrSpec));
  return (await invoke('choose', spec, text, options)) ?? null;
}

async function score(questionOrSpec, text, options) {
  checkEvidence(text);
  const spec = JSON.stringify(specOf(questionOrSpec));
  return (await invoke('score', spec, text, options)).value;
}

async function tag(questionOrSpec, text, options) {
  checkEvidence(text);
  const spec = JSON.stringify(specOf(questionOrSpec));
  return invoke('tag', spec, text, options);
}

async function filter(questionOrSpec, records, options) {
  const spec = JSON.stringify(specOf(questionOrSpec));
  const kept = await invoke('filter', spec, JSON.stringify(checkRecords(records)), options);
  return kept.map((index) => records[index]);
}

async function rank(questionOrSpec, records, options) {
  const spec = JSON.stringify(specOf(questionOrSpec));
  const ranked = await invoke('rank', spec, JSON.stringify(checkRecords(records)), options);
  return ranked.map((held) => ({ index: held.index, record: records[held.index], probability: held.probability }));
}

async function find(questionOrSpec, units, options) {
  const spec = JSON.stringify(specOf(questionOrSpec));
  const held = await invoke('find', spec, JSON.stringify(checkRecords(units)), options);
  return {
    index: held.index ?? null,
    unit: held.index === null ? null : units[held.index],
    probability: held.probability,
  };
}

function annotatedField(held) {
  if (held && typeof held === 'object') {
    if ('Decision' in held) return bare(held.Decision);
    if ('Choice' in held) return held.Choice ?? null;
    if ('Score' in held) return held.Score.value;
    if ('Tags' in held) return held.Tags;
  }
  throw new ThinkThenError('defect', `the door carried an unknown field ${JSON.stringify(held)}`, false);
}

async function annotate(set, records, options) {
  if (typeof set !== 'string' || set.length === 0) {
    throw usageError('annotate takes a question set: a file path or the set JSON');
  }
  const rows = await invoke('annotate', set, JSON.stringify(checkRecords(records)), options);
  return rows.map((row, index) => {
    const fields = {};
    for (const [name, held] of row) fields[name] = annotatedField(held);
    const record = records[index];
    return typeof record === 'string' ? { record, ...fields } : { ...record, ...fields };
  });
}

async function details(questionOrText, text, options) {
  checkEvidence(text);
  const spec = JSON.stringify(specOf(questionOrText));
  const held = await invoke('details', spec, text, options);
  return {
    probability: held.probability,
    value: bare(held.answer),
    model: held.model,
    digest: held.digest,
    sends: held.sends,
  };
}

// Return the text unchanged, for testing.
async function probe(text, options) {
  checkEvidence(text);
  return invoke('probe', null, text, options);
}

function usage() {
  return JSON.parse(native.usage());
}

function reset_usage() {
  native.resetUsage();
}

module.exports = {
  ThinkThenError,
  annotate,
  choose,
  decide,
  decide_many,
  details,
  filter,
  find,
  probe,
  question,
  rank,
  reset_usage,
  score,
  tag,
  usage,
};
