'use strict';
// The JavaScript entry over the native door. The loader (loader.cjs) is
// generated by napi-rs. This file shapes arguments into the contract's
// grammar and the contract's answers into JavaScript values, and raises the
// engine's failures as ThinkThenError. Nothing else lives here: no rule,
// no retry, no sending, and no threshold math beyond spelling a band as
// the file grammar does.

const native = require('./loader.cjs');

const QUESTION_KINDS = ['decide', 'choose', 'score', 'tag'];

/** The host's own error class. `kind` is one of the six kinds and
 * `retryable` carries the engine's verdict on a second try. A failure is
 * never a value: no call resolves `false` because it failed. */
class ThinkThenError extends Error {
  constructor(kind, message, retryable) {
    super(message);
    this.name = 'ThinkThenError';
    this.kind = kind;
    this.retryable = retryable;
  }
}

function usageError(message) {
  return new ThinkThenError('usage', message, false);
}

function isQuestion(value) {
  return typeof value === 'function' && value.__question === true;
}

// The file grammar's JSON for a question. A band given as [low, high]
// becomes the file's "low:high" string; everything else passes through and
// the engine rules on it.
function specOf(question) {
  let spec;
  if (isQuestion(question)) spec = JSON.parse(question.__spec);
  else if (typeof question === 'string') spec = { decide: question };
  else if (question && typeof question === 'object' && !Array.isArray(question)) {
    spec = { ...question };
  } else {
    throw usageError('the question is missing: text, file keys, or a question value');
  }
  if (!QUESTION_KINDS.some((kind) => Object.prototype.hasOwnProperty.call(spec, kind))) {
    throw usageError('the question names no decide, choose, score, or tag');
  }
  if (Array.isArray(spec.threshold)) {
    const [low, high] = spec.threshold;
    if (typeof low !== 'number' || typeof high !== 'number') {
      throw usageError('a band threshold is [low, high], two numbers');
    }
    spec.threshold = `${low}:${high}`;
  }
  return spec;
}

// Build a question value. A function, so no spread or stringify turns it
// back into text by accident; `__spec` holds the file grammar's JSON.
function question(spec) {
  if (!spec || typeof spec !== 'object' || Array.isArray(spec)) {
    throw usageError('question takes an object: { decide | choose | score | tag, ... }');
  }
  const held = () => {
    throw usageError('a question value is asked, not called');
  };
  held.__question = true;
  held.__spec = JSON.stringify(specOf(spec));
  return held;
}

// The ruled shape of 2026-09-21: one options object last carries the
// question's inputs and the call's options together. Each verb admits its
// own question keys; `signal` and `deadlineMs` ride the call; any other
// key is a usage error that names it.
const CALL_KEYS = new Set(['signal', 'deadlineMs']);
const QUESTION_KEYS = {
  choose: new Set(['options']),
  tag: new Set(['labels']),
  rank: new Set(['top']),
};

// Split the last object into the question's inputs and the call's options.
function splitLast(verb, options) {
  const inputs = {};
  const call = {};
  if (options === undefined || options === null) return { inputs, call };
  if (typeof options !== 'object' || Array.isArray(options)) {
    throw usageError(`${verb} takes one options object last: question inputs and call options together`);
  }
  const admitted = QUESTION_KEYS[verb] ?? new Set();
  for (const [key, value] of Object.entries(options)) {
    if (CALL_KEYS.has(key)) {
      call[key] = value;
      continue;
    }
    if (admitted.has(key)) {
      if (key === 'top' && (!Number.isInteger(value) || value < 1)) {
        throw usageError('options.top is a positive whole number');
      }
      inputs[key] = value;
      continue;
    }
    throw usageError(`options.${key} is not a ${verb} key`);
  }
  return { inputs, call };
}

// Build the question the verb asks: from a bare question string and the
// last object's inputs, or from a question value or spec as before.
function specFrom(verb, questionOrSpec, inputs) {
  if (typeof questionOrSpec !== 'string') {
    for (const key of ['options', 'labels']) {
      if (key in inputs) {
        throw usageError(`${verb}: a question value carries its own ${key}; the last object holds call options and top`);
      }
    }
    return specOf(questionOrSpec);
  }
  if (verb === 'choose') {
    if (!('options' in inputs)) {
      throw usageError('choose takes its options in the last object: { options }');
    }
    return { choose: questionOrSpec, options: inputs.options };
  }
  if (verb === 'tag') {
    if (!('labels' in inputs)) {
      throw usageError('tag takes its labels in the last object: { labels }');
    }
    return { tag: questionOrSpec, labels: inputs.labels };
  }
  return specOf(questionOrSpec);
}

function callOptions(options) {
  const out = {};
  if (options === undefined || options === null) return out;
  if (typeof options !== 'object' || Array.isArray(options)) {
    throw usageError('options is an object: { signal, deadlineMs }');
  }
  const { signal, deadlineMs } = options;
  if (signal !== undefined) {
    if (!signal || typeof signal.aborted !== 'boolean' || typeof signal.addEventListener !== 'function') {
      throw usageError('options.signal must be an AbortSignal');
    }
    const handle = new native.CancelHandle();
    const stop = () => handle.cancel();
    if (signal.aborted) stop();
    else signal.addEventListener('abort', stop, { once: true });
    out.cancel = handle;
  }
  if (deadlineMs !== undefined) {
    const held = Number(deadlineMs);
    if (!Number.isFinite(held) || held <= 0) {
      throw usageError('options.deadlineMs is positive milliseconds');
    }
    out.deadlineSec = held / 1000;
  }
  return out;
}

async function invoke(op, spec, payload, options) {
  const { cancel, deadlineSec } = callOptions(options);
  const envelope = await native.call(op, spec ?? null, payload, cancel ?? null, deadlineSec ?? null);
  const parsed = JSON.parse(envelope);
  if (parsed.err) {
    throw new ThinkThenError(parsed.err.kind, parsed.err.message, parsed.err.retryable);
  }
  return parsed.ok;
}

function bare(answer) {
  if (answer === 'yes') return true;
  if (answer === 'no') return false;
  if (answer === 'unsure') return null;
  throw new ThinkThenError('defect', `the door carried an unknown answer ${answer}`, false);
}

function checkEvidence(text) {
  if (typeof text !== 'string') throw usageError('the evidence is text');
}

function checkRecords(records) {
  if (!Array.isArray(records)) throw usageError('records is an array of strings');
  for (const held of records) {
    if (typeof held !== 'string') throw usageError('records is an array of strings');
  }
  return records;
}

async function decide(questionOrText, text, options) {
  checkEvidence(text);
  const { inputs, call } = splitLast('decide', options);
  const spec = JSON.stringify(specFrom('decide', questionOrText, inputs));
  return bare(await invoke('decide', spec, text, call));
}

// decide's bulk spelling: the same answer, once per record, in order.
async function decide_many(question, records, options) {
  const { inputs, call } = splitLast('decide_many', options);
  const spec = JSON.stringify(specFrom('decide_many', question, inputs));
  const judgments = await invoke('decide_many', spec, JSON.stringify(checkRecords(records)), call);
  return judgments.map((held) => bare(held.answer));
}

async function choose(questionOrSpec, text, options) {
  checkEvidence(text);
  const { inputs, call } = splitLast('choose', options);
  const spec = JSON.stringify(specFrom('choose', questionOrSpec, inputs));
  return (await invoke('choose', spec, text, call)) ?? null;
}

async function score(questionOrSpec, text, options) {
  checkEvidence(text);
  const { inputs, call } = splitLast('score', options);
  const spec = JSON.stringify(specFrom('score', questionOrSpec, inputs));
  return (await invoke('score', spec, text, call)).value;
}

async function tag(questionOrSpec, text, options) {
  checkEvidence(text);
  const { inputs, call } = splitLast('tag', options);
  const spec = JSON.stringify(specFrom('tag', questionOrSpec, inputs));
  return invoke('tag', spec, text, call);
}

async function filter(questionOrSpec, records, options) {
  const { inputs, call } = splitLast('filter', options);
  const spec = JSON.stringify(specFrom('filter', questionOrSpec, inputs));
  const kept = await invoke('filter', spec, JSON.stringify(checkRecords(records)), call);
  return kept.map((index) => records[index]);
}

async function rank(questionOrSpec, records, options) {
  const { inputs, call } = splitLast('rank', options);
  const spec = JSON.stringify(specFrom('rank', questionOrSpec, inputs));
  const ranked = await invoke('rank', spec, JSON.stringify(checkRecords(records)), call);
  const ordered = ranked.map((held) => ({ index: held.index, record: records[held.index], probability: held.probability }));
  return inputs.top === undefined ? ordered : ordered.slice(0, inputs.top);
}

async function find(questionOrSpec, units, options) {
  const { inputs, call } = splitLast('find', options);
  const spec = JSON.stringify(specFrom('find', questionOrSpec, inputs));
  const held = await invoke('find', spec, JSON.stringify(checkRecords(units)), call);
  return {
    index: held.index ?? null,
    unit: held.index === null ? null : units[held.index],
    probability: held.probability,
  };
}

function annotatedField(held) {
  if (held && typeof held === 'object') {
    if ('Decision' in held) return bare(held.Decision);
    if ('Choice' in held) return held.Choice ?? null;
    if ('Score' in held) return held.Score.value;
    if ('Tags' in held) return held.Tags;
  }
  throw new ThinkThenError('defect', `the door carried an unknown field ${JSON.stringify(held)}`, false);
}

async function annotate(set, records, options) {
  if (typeof set !== 'string' || set.length === 0) {
    throw usageError('annotate takes a question set: a file path or the set JSON');
  }
  const { call } = splitLast('annotate', options);
  const rows = await invoke('annotate', set, JSON.stringify(checkRecords(records)), call);
  return rows.map((row, index) => {
    const fields = {};
    for (const [name, held] of row) fields[name] = annotatedField(held);
    const record = records[index];
    return typeof record === 'string' ? { record, ...fields } : { ...record, ...fields };
  });
}

async function details(questionOrText, text, options) {
  checkEvidence(text);
  const { inputs, call } = splitLast('details', options);
  const spec = JSON.stringify(specFrom('details', questionOrText, inputs));
  const held = await invoke('details', spec, text, call);
  return {
    probability: held.probability,
    value: bare(held.answer),
    model: held.model,
    digest: held.digest,
    sends: held.sends,
  };
}

function usage() {
  return JSON.parse(native.usage());
}

function reset_usage() {
  native.resetUsage();
}

module.exports = {
  ThinkThenError,
  annotate,
  choose,
  decide,
  decide_many,
  details,
  filter,
  find,
  question,
  rank,
  reset_usage,
  score,
  tag,
  usage,
};
