/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** The counters since the last reset, as the contract's JSON. */
export declare function usage(): string
/** Reset the counters. */
export declare function resetUsage(): void
/**
 * One call on a worker thread. `op` names the verb; `spec` is the
 * question's file-grammar JSON (or, for `annotate`, a set's path or
 * JSON); `payload` is one evidence text or a JSON array of records;
 * `cancel` carries the wrapper's `AbortSignal`; `deadlineSec` bounds the
 * whole call.
 */
export declare function call(op: string, spec: string | undefined | null, payload: string, cancel?: CancelHandle | undefined | null, deadlineSec?: number | undefined | null): Promise<unknown>
/**
 * A cancel token the wrapper holds. The same token rides into the task,
 * so an `AbortSignal` listener can stop a running batch from JavaScript.
 */
export declare class CancelHandle {
  constructor()
  /** Ask every wait that sees this token to stop. */
  cancel(): void
  /** Whether `cancel` has been called. */
  get cancelled(): boolean
}
